// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_xf_QuatizationDithering_17_9_1080_1920_256_1024_1_3_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        lsc_out_data218_dout,
        lsc_out_data218_num_data_valid,
        lsc_out_data218_fifo_cap,
        lsc_out_data218_empty_n,
        lsc_out_data218_read,
        aecin_data220_din,
        aecin_data220_num_data_valid,
        aecin_data220_fifo_cap,
        aecin_data220_full_n,
        aecin_data220_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [29:0] lsc_out_data218_dout;
input  [2:0] lsc_out_data218_num_data_valid;
input  [2:0] lsc_out_data218_fifo_cap;
input   lsc_out_data218_empty_n;
output   lsc_out_data218_read;
output  [23:0] aecin_data220_din;
input  [2:0] aecin_data220_num_data_valid;
input  [2:0] aecin_data220_fifo_cap;
input   aecin_data220_full_n;
output   aecin_data220_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg lsc_out_data218_read;
reg aecin_data220_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [15:0] in_col_loop_bound_fu_79_p2;
reg   [15:0] in_col_loop_bound_reg_116;
wire    ap_CS_fsm_state2;
wire   [16:0] sub238_fu_95_p2;
reg   [16:0] sub238_reg_132;
wire    ap_CS_fsm_state5;
wire  signed [31:0] grp_fu_102_p2;
reg   [31:0] bound_reg_137;
reg   [10:0] offset_buffer_V_address0;
reg    offset_buffer_V_ce0;
reg    offset_buffer_V_we0;
reg   [8:0] offset_buffer_V_d0;
reg    offset_buffer_V_ce1;
wire   [8:0] offset_buffer_V_q1;
reg   [10:0] offset_buffer_V_1_address0;
reg    offset_buffer_V_1_ce0;
reg    offset_buffer_V_1_we0;
reg   [8:0] offset_buffer_V_1_d0;
reg    offset_buffer_V_1_ce1;
wire   [8:0] offset_buffer_V_1_q1;
reg   [10:0] offset_buffer_V_2_address0;
reg    offset_buffer_V_2_ce0;
reg    offset_buffer_V_2_we0;
reg   [8:0] offset_buffer_V_2_d0;
reg    offset_buffer_V_2_ce1;
wire   [8:0] offset_buffer_V_2_q1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_done;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_idle;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_ready;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_address0;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_ce0;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_we0;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_d0;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_address0;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_ce0;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_we0;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_d0;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_address0;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_ce0;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_we0;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_d0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_idle;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_ready;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_lsc_out_data218_read;
wire   [23:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_aecin_data220_din;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_aecin_data220_write;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_ce0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_we0;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_d0;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_ce1;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_ce0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_we0;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_d0;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_ce1;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_ce0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_we0;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_d0;
wire   [10:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_ce1;
reg    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    ap_block_state1;
wire  signed [16:0] in_col_loop_bound_cast_fu_92_p1;
wire   [15:0] grp_fu_102_p0;
wire   [15:0] grp_fu_102_p1;
reg    grp_fu_102_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire   [31:0] grp_fu_102_p00;
wire   [31:0] grp_fu_102_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start_reg = 1'b0;
#0 grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start_reg = 1'b0;
end

ISPPipeline_accel_xf_QuatizationDithering_17_9_1080_1920_256_1024_1_3_3_s_offset_buffer_V_RAM_Ahbi #(
    .DataWidth( 9 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
offset_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(offset_buffer_V_address0),
    .ce0(offset_buffer_V_ce0),
    .we0(offset_buffer_V_we0),
    .d0(offset_buffer_V_d0),
    .address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_address1),
    .ce1(offset_buffer_V_ce1),
    .q1(offset_buffer_V_q1)
);

ISPPipeline_accel_xf_QuatizationDithering_17_9_1080_1920_256_1024_1_3_3_s_offset_buffer_V_RAM_Ahbi #(
    .DataWidth( 9 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
offset_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(offset_buffer_V_1_address0),
    .ce0(offset_buffer_V_1_ce0),
    .we0(offset_buffer_V_1_we0),
    .d0(offset_buffer_V_1_d0),
    .address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_address1),
    .ce1(offset_buffer_V_1_ce1),
    .q1(offset_buffer_V_1_q1)
);

ISPPipeline_accel_xf_QuatizationDithering_17_9_1080_1920_256_1024_1_3_3_s_offset_buffer_V_RAM_Ahbi #(
    .DataWidth( 9 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
offset_buffer_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(offset_buffer_V_2_address0),
    .ce0(offset_buffer_V_2_ce0),
    .we0(offset_buffer_V_2_we0),
    .d0(offset_buffer_V_2_d0),
    .address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_address1),
    .ce1(offset_buffer_V_2_ce1),
    .q1(offset_buffer_V_2_q1)
);

ISPPipeline_accel_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1 grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start),
    .ap_done(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_done),
    .ap_idle(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_idle),
    .ap_ready(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_ready),
    .p_read1(p_read1),
    .offset_buffer_V_2_address0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_address0),
    .offset_buffer_V_2_ce0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_ce0),
    .offset_buffer_V_2_we0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_we0),
    .offset_buffer_V_2_d0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_d0),
    .offset_buffer_V_1_address0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_address0),
    .offset_buffer_V_1_ce0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_ce0),
    .offset_buffer_V_1_we0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_we0),
    .offset_buffer_V_1_d0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_d0),
    .offset_buffer_V_address0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_address0),
    .offset_buffer_V_ce0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_ce0),
    .offset_buffer_V_we0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_we0),
    .offset_buffer_V_d0(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_d0)
);

ISPPipeline_accel_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start),
    .ap_done(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done),
    .ap_idle(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_idle),
    .ap_ready(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_ready),
    .lsc_out_data218_dout(lsc_out_data218_dout),
    .lsc_out_data218_num_data_valid(3'd0),
    .lsc_out_data218_fifo_cap(3'd0),
    .lsc_out_data218_empty_n(lsc_out_data218_empty_n),
    .lsc_out_data218_read(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_lsc_out_data218_read),
    .aecin_data220_din(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_aecin_data220_din),
    .aecin_data220_num_data_valid(3'd0),
    .aecin_data220_fifo_cap(3'd0),
    .aecin_data220_full_n(aecin_data220_full_n),
    .aecin_data220_write(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_aecin_data220_write),
    .in_col_loop_bound(in_col_loop_bound_reg_116),
    .bound(bound_reg_137),
    .offset_buffer_V_2_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_address0),
    .offset_buffer_V_2_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_ce0),
    .offset_buffer_V_2_we0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_we0),
    .offset_buffer_V_2_d0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_d0),
    .offset_buffer_V_2_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_address1),
    .offset_buffer_V_2_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_ce1),
    .offset_buffer_V_2_q1(offset_buffer_V_2_q1),
    .offset_buffer_V_1_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_address0),
    .offset_buffer_V_1_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_ce0),
    .offset_buffer_V_1_we0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_we0),
    .offset_buffer_V_1_d0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_d0),
    .offset_buffer_V_1_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_address1),
    .offset_buffer_V_1_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_ce1),
    .offset_buffer_V_1_q1(offset_buffer_V_1_q1),
    .sub238(sub238_reg_132),
    .offset_buffer_V_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_address0),
    .offset_buffer_V_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_ce0),
    .offset_buffer_V_we0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_we0),
    .offset_buffer_V_d0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_d0),
    .offset_buffer_V_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_address1),
    .offset_buffer_V_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_ce1),
    .offset_buffer_V_q1(offset_buffer_V_q1),
    .p_read1(p_read1)
);

ISPPipeline_accel_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U405(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_102_p0),
    .din1(grp_fu_102_p1),
    .ce(grp_fu_102_ce),
    .dout(grp_fu_102_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_ready == 1'b1)) begin
            grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_ready == 1'b1)) begin
            grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bound_reg_137 <= grp_fu_102_p2;
        sub238_reg_132 <= sub238_fu_95_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_col_loop_bound_reg_116 <= in_col_loop_bound_fu_79_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        aecin_data220_write = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_aecin_data220_write;
    end else begin
        aecin_data220_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state3) & (grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_done == 1'b0)))) begin
        grp_fu_102_ce = 1'b0;
    end else begin
        grp_fu_102_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        lsc_out_data218_read = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_lsc_out_data218_read;
    end else begin
        lsc_out_data218_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_1_address0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_1_address0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_address0;
    end else begin
        offset_buffer_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_1_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_1_ce0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_ce0;
    end else begin
        offset_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_1_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_ce1;
    end else begin
        offset_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_1_d0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_1_d0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_d0;
    end else begin
        offset_buffer_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_1_we0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_1_we0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_1_we0;
    end else begin
        offset_buffer_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_2_address0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_2_address0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_address0;
    end else begin
        offset_buffer_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_2_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_2_ce0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_ce0;
    end else begin
        offset_buffer_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_2_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_ce1;
    end else begin
        offset_buffer_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_2_d0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_2_d0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_d0;
    end else begin
        offset_buffer_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_2_we0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_2_we0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_2_we0;
    end else begin
        offset_buffer_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_address0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_address0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_address0;
    end else begin
        offset_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_ce0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_ce0;
    end else begin
        offset_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_ce1;
    end else begin
        offset_buffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_d0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_d0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_d0;
    end else begin
        offset_buffer_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        offset_buffer_V_we0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_offset_buffer_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_V_we0 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_offset_buffer_V_we0;
    end else begin
        offset_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign aecin_data220_din = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_aecin_data220_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_fu_102_p0 = grp_fu_102_p00;

assign grp_fu_102_p00 = p_read;

assign grp_fu_102_p1 = grp_fu_102_p10;

assign grp_fu_102_p10 = $unsigned(in_col_loop_bound_fu_79_p2);

assign grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_64_ap_start_reg;

assign grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_118_1_fu_56_ap_start_reg;

assign in_col_loop_bound_cast_fu_92_p1 = $signed(in_col_loop_bound_reg_116);

assign in_col_loop_bound_fu_79_p2 = (p_read1 + 16'd1);

assign sub238_fu_95_p2 = ($signed(in_col_loop_bound_cast_fu_92_p1) + $signed(17'd131071));

endmodule //ISPPipeline_accel_xf_QuatizationDithering_17_9_1080_1920_256_1024_1_3_3_s
