// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        demosaic_out_data216_dout,
        demosaic_out_data216_num_data_valid,
        demosaic_out_data216_fifo_cap,
        demosaic_out_data216_empty_n,
        demosaic_out_data216_read,
        impop_data1_din,
        impop_data1_num_data_valid,
        impop_data1_fifo_cap,
        impop_data1_full_n,
        impop_data1_write,
        hist_0_address0,
        hist_0_ce0,
        hist_0_we0,
        hist_0_d0,
        hist_1_address0,
        hist_1_ce0,
        hist_1_we0,
        hist_1_d0,
        hist_2_address0,
        hist_2_ce0,
        hist_2_we0,
        hist_2_d0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [29:0] demosaic_out_data216_dout;
input  [2:0] demosaic_out_data216_num_data_valid;
input  [2:0] demosaic_out_data216_fifo_cap;
input   demosaic_out_data216_empty_n;
output   demosaic_out_data216_read;
output  [29:0] impop_data1_din;
input  [2:0] impop_data1_num_data_valid;
input  [2:0] impop_data1_fifo_cap;
input   impop_data1_full_n;
output   impop_data1_write;
output  [9:0] hist_0_address0;
output   hist_0_ce0;
output   hist_0_we0;
output  [31:0] hist_0_d0;
output  [9:0] hist_1_address0;
output   hist_1_ce0;
output   hist_1_we0;
output  [31:0] hist_1_d0;
output  [9:0] hist_2_address0;
output   hist_2_ce0;
output   hist_2_we0;
output  [31:0] hist_2_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg demosaic_out_data216_read;
reg impop_data1_write;
reg[9:0] hist_0_address0;
reg hist_0_ce0;
reg hist_0_we0;
reg[31:0] hist_0_d0;
reg[9:0] hist_1_address0;
reg hist_1_ce0;
reg hist_1_we0;
reg[31:0] hist_1_d0;
reg[9:0] hist_2_address0;
reg hist_2_ce0;
reg hist_2_we0;
reg[31:0] hist_2_d0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_5;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_2;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_11;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_8;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_4;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_1;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_10;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_7;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_3;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_9;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_6;
wire    ap_CS_fsm_state2;
wire   [16:0] p_read1_cast_fu_410_p1;
reg   [16:0] p_read1_cast_reg_683;
wire   [0:0] cmp6214_fu_414_p2;
reg   [0:0] cmp6214_reg_688;
wire   [15:0] row_2_fu_428_p2;
reg   [15:0] row_2_reg_695;
wire    ap_CS_fsm_state3;
reg   [15:0] tmp_56_reg_700;
wire   [0:0] icmp_ln531_fu_423_p2;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_36_reg_705;
wire    ap_CS_fsm_state4;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_37_reg_710;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_38_reg_715;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_39_reg_720;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_40_reg_725;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_41_reg_730;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_42_reg_735;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_43_reg_740;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_44_reg_745;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_45_reg_750;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_46_reg_755;
reg   [31:0] void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_47_reg_760;
wire   [16:0] tmp_57_fu_479_p3;
reg   [16:0] tmp_57_reg_765;
reg   [9:0] tmp_hist_V_address0;
reg    tmp_hist_V_ce0;
reg    tmp_hist_V_we0;
reg   [31:0] tmp_hist_V_d0;
wire   [31:0] tmp_hist_V_q0;
reg   [9:0] tmp_hist_V_1_address0;
reg    tmp_hist_V_1_ce0;
reg    tmp_hist_V_1_we0;
reg   [31:0] tmp_hist_V_1_d0;
wire   [31:0] tmp_hist_V_1_q0;
reg   [9:0] tmp_hist_V_2_address0;
reg    tmp_hist_V_2_ce0;
reg    tmp_hist_V_2_we0;
reg   [31:0] tmp_hist_V_2_d0;
wire   [31:0] tmp_hist_V_2_q0;
reg   [9:0] tmp_hist1_V_address0;
reg    tmp_hist1_V_ce0;
reg    tmp_hist1_V_we0;
reg   [31:0] tmp_hist1_V_d0;
wire   [31:0] tmp_hist1_V_q0;
reg   [9:0] tmp_hist1_V_1_address0;
reg    tmp_hist1_V_1_ce0;
reg    tmp_hist1_V_1_we0;
reg   [31:0] tmp_hist1_V_1_d0;
wire   [31:0] tmp_hist1_V_1_q0;
reg   [9:0] tmp_hist1_V_2_address0;
reg    tmp_hist1_V_2_ce0;
reg    tmp_hist1_V_2_we0;
reg   [31:0] tmp_hist1_V_2_d0;
wire   [31:0] tmp_hist1_V_2_q0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_done;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_idle;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_ready;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_address0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_ce0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_address0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_ce0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_address0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_ce0;
wire    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_d0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_done;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_idle;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_ready;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_address0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_ce0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_address0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_ce0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_address0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_ce0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_address0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_ce0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_address0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_ce0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_address0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_ce0;
wire    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_d0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_done;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_idle;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_ready;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_demosaic_out_data216_read;
wire   [29:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_impop_data1_din;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_impop_data1_write;
wire   [9:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_address0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_ce0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_we0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_d0;
wire   [9:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_address0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_ce0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_we0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_d0;
wire   [9:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_address0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_ce0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_we0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_d0;
wire   [9:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_address0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_ce0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_we0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_d0;
wire   [9:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_address0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_ce0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_we0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_d0;
wire   [9:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_address0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_ce0;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_we0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_d0;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_4_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_4_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_4_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_4_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_5_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_5_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_5_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_5_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_2_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_2_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_2_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_2_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_4_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_4_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_4_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_4_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_3_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_3_out_ap_vld;
wire   [31:0] grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_3_out;
wire    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_3_out_ap_vld;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_done;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_idle;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_ready;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_ce0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_ce0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_ce0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_we0;
wire   [31:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_d0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_ce0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_ce0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_1_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_1_ce0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_1_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_1_ce0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_2_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_2_ce0;
wire   [9:0] grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_2_address0;
wire    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_2_ce0;
reg    grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start_reg;
reg    grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start_reg;
reg    grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln597_fu_449_p1;
wire   [63:0] zext_ln598_fu_454_p1;
wire   [63:0] zext_ln597_1_fu_459_p1;
wire   [63:0] zext_ln598_1_fu_464_p1;
wire   [63:0] zext_ln597_2_fu_469_p1;
wire   [63:0] zext_ln598_2_fu_474_p1;
wire    ap_CS_fsm_state6;
reg   [15:0] row_fu_98;
reg    ap_block_state2_on_subcall_done;
wire   [16:0] add_ln537_fu_434_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_5 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_2 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_11 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_8 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_4 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_1 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_10 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_7 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_3 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_9 = 32'd0;
#0 void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_6 = 32'd0;
#0 grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start_reg = 1'b0;
#0 grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start_reg = 1'b0;
#0 grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start_reg = 1'b0;
#0 grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start_reg = 1'b0;
end

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s_tmp_hist_V_RAM_T2P_BRAM_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tmp_hist_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist_V_address0),
    .ce0(tmp_hist_V_ce0),
    .we0(tmp_hist_V_we0),
    .d0(tmp_hist_V_d0),
    .q0(tmp_hist_V_q0)
);

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s_tmp_hist_V_RAM_T2P_BRAM_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tmp_hist_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist_V_1_address0),
    .ce0(tmp_hist_V_1_ce0),
    .we0(tmp_hist_V_1_we0),
    .d0(tmp_hist_V_1_d0),
    .q0(tmp_hist_V_1_q0)
);

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s_tmp_hist_V_RAM_T2P_BRAM_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tmp_hist_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist_V_2_address0),
    .ce0(tmp_hist_V_2_ce0),
    .we0(tmp_hist_V_2_we0),
    .d0(tmp_hist_V_2_d0),
    .q0(tmp_hist_V_2_q0)
);

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s_tmp_hist_V_RAM_T2P_BRAM_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tmp_hist1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist1_V_address0),
    .ce0(tmp_hist1_V_ce0),
    .we0(tmp_hist1_V_we0),
    .d0(tmp_hist1_V_d0),
    .q0(tmp_hist1_V_q0)
);

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s_tmp_hist_V_RAM_T2P_BRAM_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tmp_hist1_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist1_V_1_address0),
    .ce0(tmp_hist1_V_1_ce0),
    .we0(tmp_hist1_V_1_we0),
    .d0(tmp_hist1_V_1_d0),
    .q0(tmp_hist1_V_1_q0)
);

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s_tmp_hist_V_RAM_T2P_BRAM_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tmp_hist1_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist1_V_2_address0),
    .ce0(tmp_hist1_V_2_ce0),
    .we0(tmp_hist1_V_2_we0),
    .d0(tmp_hist1_V_2_d0),
    .q0(tmp_hist1_V_2_q0)
);

ISPPipeline_accel_AWBhistogramkernel_Pipeline_INITIALIZE_HIST grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start),
    .ap_done(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_done),
    .ap_idle(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_idle),
    .ap_ready(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_ready),
    .hist_2_address0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_address0),
    .hist_2_ce0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_ce0),
    .hist_2_we0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_we0),
    .hist_2_d0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_d0),
    .hist_1_address0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_address0),
    .hist_1_ce0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_ce0),
    .hist_1_we0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_we0),
    .hist_1_d0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_d0),
    .hist_0_address0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_address0),
    .hist_0_ce0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_ce0),
    .hist_0_we0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_we0),
    .hist_0_d0(grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_d0)
);

ISPPipeline_accel_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start),
    .ap_done(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_done),
    .ap_idle(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_idle),
    .ap_ready(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_ready),
    .tmp_hist1_V_2_address0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_address0),
    .tmp_hist1_V_2_ce0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_ce0),
    .tmp_hist1_V_2_we0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_we0),
    .tmp_hist1_V_2_d0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_d0),
    .tmp_hist1_V_1_address0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_address0),
    .tmp_hist1_V_1_ce0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_ce0),
    .tmp_hist1_V_1_we0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_we0),
    .tmp_hist1_V_1_d0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_d0),
    .tmp_hist1_V_address0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_address0),
    .tmp_hist1_V_ce0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_ce0),
    .tmp_hist1_V_we0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_we0),
    .tmp_hist1_V_d0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_d0),
    .tmp_hist_V_2_address0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_address0),
    .tmp_hist_V_2_ce0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_ce0),
    .tmp_hist_V_2_we0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_we0),
    .tmp_hist_V_2_d0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_d0),
    .tmp_hist_V_1_address0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_address0),
    .tmp_hist_V_1_ce0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_ce0),
    .tmp_hist_V_1_we0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_we0),
    .tmp_hist_V_1_d0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_d0),
    .tmp_hist_V_address0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_address0),
    .tmp_hist_V_ce0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_ce0),
    .tmp_hist_V_we0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_we0),
    .tmp_hist_V_d0(grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_d0)
);

ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start),
    .ap_done(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_done),
    .ap_idle(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_idle),
    .ap_ready(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_ready),
    .demosaic_out_data216_dout(demosaic_out_data216_dout),
    .demosaic_out_data216_num_data_valid(3'd0),
    .demosaic_out_data216_fifo_cap(3'd0),
    .demosaic_out_data216_empty_n(demosaic_out_data216_empty_n),
    .demosaic_out_data216_read(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_demosaic_out_data216_read),
    .impop_data1_din(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_impop_data1_din),
    .impop_data1_num_data_valid(3'd0),
    .impop_data1_fifo_cap(3'd0),
    .impop_data1_full_n(impop_data1_full_n),
    .impop_data1_write(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_impop_data1_write),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_23(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_47_reg_760),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_22(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_46_reg_755),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_21(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_45_reg_750),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_20(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_44_reg_745),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_19(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_43_reg_740),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_18(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_42_reg_735),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_17(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_41_reg_730),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_16(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_40_reg_725),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_15(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_39_reg_720),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_14(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_38_reg_715),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_13(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_37_reg_710),
    .void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_12(void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_36_reg_705),
    .empty(tmp_57_reg_765),
    .tmp_hist_V_address0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_address0),
    .tmp_hist_V_ce0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_ce0),
    .tmp_hist_V_we0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_we0),
    .tmp_hist_V_d0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_d0),
    .tmp_hist_V_q0(tmp_hist_V_q0),
    .tmp_hist1_V_address0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_address0),
    .tmp_hist1_V_ce0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_ce0),
    .tmp_hist1_V_we0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_we0),
    .tmp_hist1_V_d0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_d0),
    .tmp_hist1_V_q0(tmp_hist1_V_q0),
    .tmp_hist_V_1_address0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_address0),
    .tmp_hist_V_1_ce0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_ce0),
    .tmp_hist_V_1_we0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_we0),
    .tmp_hist_V_1_d0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_d0),
    .tmp_hist_V_1_q0(tmp_hist_V_1_q0),
    .tmp_hist1_V_1_address0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_address0),
    .tmp_hist1_V_1_ce0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_ce0),
    .tmp_hist1_V_1_we0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_we0),
    .tmp_hist1_V_1_d0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_d0),
    .tmp_hist1_V_1_q0(tmp_hist1_V_1_q0),
    .tmp_hist_V_2_address0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_address0),
    .tmp_hist_V_2_ce0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_ce0),
    .tmp_hist_V_2_we0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_we0),
    .tmp_hist_V_2_d0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_d0),
    .tmp_hist_V_2_q0(tmp_hist_V_2_q0),
    .tmp_hist1_V_2_address0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_address0),
    .tmp_hist1_V_2_ce0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_ce0),
    .tmp_hist1_V_2_we0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_we0),
    .tmp_hist1_V_2_d0(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_d0),
    .tmp_hist1_V_2_q0(tmp_hist1_V_2_q0),
    .tmp_acc1_4_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_4_out),
    .tmp_acc1_4_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_4_out_ap_vld),
    .tmp_acc_4_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_4_out),
    .tmp_acc_4_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_4_out_ap_vld),
    .tmp1_5_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_5_out),
    .tmp1_5_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_5_out_ap_vld),
    .tmp_5_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_5_out),
    .tmp_5_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_5_out_ap_vld),
    .tmp_acc1_2_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_2_out),
    .tmp_acc1_2_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_2_out_ap_vld),
    .tmp_acc_2_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_2_out),
    .tmp_acc_2_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_2_out_ap_vld),
    .tmp1_4_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_4_out),
    .tmp1_4_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_4_out_ap_vld),
    .tmp_4_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_4_out),
    .tmp_4_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_4_out_ap_vld),
    .tmp_acc1_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_out),
    .tmp_acc1_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_out_ap_vld),
    .tmp_acc_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_out),
    .tmp_acc_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_out_ap_vld),
    .tmp1_3_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_3_out),
    .tmp1_3_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_3_out_ap_vld),
    .tmp_3_out(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_3_out),
    .tmp_3_out_ap_vld(grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_3_out_ap_vld)
);

ISPPipeline_accel_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start),
    .ap_done(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_done),
    .ap_idle(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_idle),
    .ap_ready(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_ready),
    .hist_2_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_address0),
    .hist_2_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_ce0),
    .hist_2_we0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_we0),
    .hist_2_d0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_d0),
    .hist_1_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_address0),
    .hist_1_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_ce0),
    .hist_1_we0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_we0),
    .hist_1_d0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_d0),
    .hist_0_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_address0),
    .hist_0_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_ce0),
    .hist_0_we0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_we0),
    .hist_0_d0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_d0),
    .tmp_hist_V_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_address0),
    .tmp_hist_V_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_ce0),
    .tmp_hist_V_q0(tmp_hist_V_q0),
    .tmp_hist1_V_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_address0),
    .tmp_hist1_V_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_ce0),
    .tmp_hist1_V_q0(tmp_hist1_V_q0),
    .tmp_hist_V_1_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_1_address0),
    .tmp_hist_V_1_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_1_ce0),
    .tmp_hist_V_1_q0(tmp_hist_V_1_q0),
    .tmp_hist1_V_1_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_1_address0),
    .tmp_hist1_V_1_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_1_ce0),
    .tmp_hist1_V_1_q0(tmp_hist1_V_1_q0),
    .tmp_hist_V_2_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_2_address0),
    .tmp_hist_V_2_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_2_ce0),
    .tmp_hist_V_2_q0(tmp_hist_V_2_q0),
    .tmp_hist1_V_2_address0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_2_address0),
    .tmp_hist1_V_2_ce0(grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_2_ce0),
    .tmp_hist1_V_2_q0(tmp_hist1_V_2_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start_reg <= 1'b1;
        end else if ((grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_ready == 1'b1)) begin
            grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_ready == 1'b1)) begin
            grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start_reg <= 1'b1;
        end else if ((grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_ready == 1'b1)) begin
            grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start_reg <= 1'b1;
        end else if ((grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_ready == 1'b1)) begin
            grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_fu_98 <= 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_fu_98 <= row_2_reg_695;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp6214_reg_688 <= cmp6214_fu_414_p2;
        p_read1_cast_reg_683[15 : 0] <= p_read1_cast_fu_410_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        row_2_reg_695 <= row_2_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln531_fu_423_p2 == 1'd0) & (cmp6214_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_56_reg_700 <= {{add_ln537_fu_434_p2[16:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_57_reg_765[16 : 1] <= tmp_57_fu_479_p3[16 : 1];
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_36_reg_705 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_5;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_37_reg_710 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_2;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_38_reg_715 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_11;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_39_reg_720 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_8;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_40_reg_725 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_4;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_41_reg_730 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_1;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_42_reg_735 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_10;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_43_reg_740 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_7;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_44_reg_745 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_3;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_45_reg_750 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_46_reg_755 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_9;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_47_reg_760 <= void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_6;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp6214_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_5_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_1 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_4_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_10 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_2_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_11 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_2 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp1_3_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_3 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_5_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_4 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_4_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_5 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_3_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_6 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_4_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_7 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_2_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_8 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc1_out;
        void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_9 <= grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_acc_4_out;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        demosaic_out_data216_read = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_demosaic_out_data216_read;
    end else begin
        demosaic_out_data216_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_0_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_0_address0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_address0;
    end else begin
        hist_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_0_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_0_ce0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_ce0;
    end else begin
        hist_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_0_d0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_0_d0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_d0;
    end else begin
        hist_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_0_we0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_0_we0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_0_we0;
    end else begin
        hist_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_1_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_1_address0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_address0;
    end else begin
        hist_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_1_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_1_ce0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_ce0;
    end else begin
        hist_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_1_d0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_1_d0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_d0;
    end else begin
        hist_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_1_we0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_1_we0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_1_we0;
    end else begin
        hist_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_2_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_2_address0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_address0;
    end else begin
        hist_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_2_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_2_ce0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_ce0;
    end else begin
        hist_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_2_d0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_2_d0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_d0;
    end else begin
        hist_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hist_2_we0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_hist_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_2_we0 = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_hist_2_we0;
    end else begin
        hist_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        impop_data1_write = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_impop_data1_write;
    end else begin
        impop_data1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_1_address0 = zext_ln598_1_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist1_V_1_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_1_address0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_1_address0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_address0;
    end else begin
        tmp_hist1_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist1_V_1_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_1_ce0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_1_ce0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_ce0;
    end else begin
        tmp_hist1_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_1_d0 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_7;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_1_d0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_1_d0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_d0;
    end else begin
        tmp_hist1_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_fu_423_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_hist1_V_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_1_we0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_1_we0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_1_we0;
    end else begin
        tmp_hist1_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_2_address0 = zext_ln598_2_fu_474_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist1_V_2_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_2_address0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_2_address0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_address0;
    end else begin
        tmp_hist1_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist1_V_2_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_2_ce0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_2_ce0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_ce0;
    end else begin
        tmp_hist1_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_2_d0 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_6;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_2_d0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_2_d0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_d0;
    end else begin
        tmp_hist1_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_fu_423_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_hist1_V_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_2_we0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_2_we0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_2_we0;
    end else begin
        tmp_hist1_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_address0 = zext_ln598_fu_454_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist1_V_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_address0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_address0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_address0;
    end else begin
        tmp_hist1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist1_V_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist1_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_ce0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_ce0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_ce0;
    end else begin
        tmp_hist1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_V_d0 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_8;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_d0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_d0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_d0;
    end else begin
        tmp_hist1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_fu_423_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_hist1_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist1_V_we0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist1_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist1_V_we0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist1_V_we0;
    end else begin
        tmp_hist1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_1_address0 = zext_ln597_1_fu_459_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist_V_1_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_1_address0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_1_address0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_address0;
    end else begin
        tmp_hist_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist_V_1_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_1_ce0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_1_ce0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_ce0;
    end else begin
        tmp_hist_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_1_d0 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_1_d0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_1_d0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_d0;
    end else begin
        tmp_hist_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_fu_423_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_hist_V_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_1_we0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_1_we0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_1_we0;
    end else begin
        tmp_hist_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_2_address0 = zext_ln597_2_fu_469_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist_V_2_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_2_address0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_2_address0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_address0;
    end else begin
        tmp_hist_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist_V_2_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_2_ce0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_2_ce0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_ce0;
    end else begin
        tmp_hist_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_2_d0 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_9;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_2_d0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_2_d0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_d0;
    end else begin
        tmp_hist_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_fu_423_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_hist_V_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_2_we0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_2_we0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_2_we0;
    end else begin
        tmp_hist_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_address0 = zext_ln597_fu_449_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist_V_address0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_address0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_address0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_address0;
    end else begin
        tmp_hist_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_hist_V_ce0 = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_tmp_hist_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_ce0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_ce0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_ce0;
    end else begin
        tmp_hist_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist_V_d0 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_d0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_d0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_d0;
    end else begin
        tmp_hist_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_fu_423_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_hist_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_hist_V_we0 = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_tmp_hist_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_hist_V_we0 = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_tmp_hist_V_we0;
    end else begin
        tmp_hist_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln531_fu_423_p2 == 1'd0) & (cmp6214_reg_688 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((icmp_ln531_fu_423_p2 == 1'd0) & (cmp6214_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln537_fu_434_p2 = (p_read1_cast_reg_683 + 17'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_done == 1'b0) | (grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_done == 1'b0));
end

assign cmp6214_fu_414_p2 = ((p_read1 == 16'd0) ? 1'b1 : 1'b0);

assign grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_ap_start_reg;

assign grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start = grp_AWBhistogramkernel_Pipeline_HIST_INITIALIZE_LOOP_fu_268_ap_start_reg;

assign grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start = grp_AWBhistogramkernel_Pipeline_INITIALIZE_HIST_fu_258_ap_start_reg;

assign grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start = grp_AWBhistogramkernel_Pipeline_MERGE_HIST_LOOP_fu_323_ap_start_reg;

assign icmp_ln531_fu_423_p2 = ((row_fu_98 == p_read) ? 1'b1 : 1'b0);

assign impop_data1_din = grp_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_Pipeline_COL_LOOP_fu_284_impop_data1_din;

assign p_read1_cast_fu_410_p1 = p_read1;

assign row_2_fu_428_p2 = (row_fu_98 + 16'd1);

assign tmp_57_fu_479_p3 = {{tmp_56_reg_700}, {1'd0}};

assign zext_ln597_1_fu_459_p1 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_4;

assign zext_ln597_2_fu_469_p1 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_3;

assign zext_ln597_fu_449_p1 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_5;

assign zext_ln598_1_fu_464_p1 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_1;

assign zext_ln598_2_fu_474_p1 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float;

assign zext_ln598_fu_454_p1 = void_AWBhistogramkernel_Mat_Mat_unsigned_int_1024_float_float_float_float_2;

always @ (posedge ap_clk) begin
    p_read1_cast_reg_683[16] <= 1'b0;
    tmp_57_reg_765[0] <= 1'b0;
end

endmodule //ISPPipeline_accel_AWBhistogramkernel_17_17_1080_1920_1_3_3_21_1_1024_s
