# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_lite_led_simu/axi_lite_led_simu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_lite_led_simu || ORIG_REF_NAME==axi_lite_led_simu} -quiet] -quiet

# IP: bd/axi_lite_led_simu/ip/axi_lite_led_simu_axi_lite_led_0_0/axi_lite_led_simu_axi_lite_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_lite_led_simu_axi_lite_led_0_0 || ORIG_REF_NAME==axi_lite_led_simu_axi_lite_led_0_0} -quiet] -quiet

# XDC: /home/aspera/Projet_led/Projet_led.gen/sources_1/bd/axi_lite_led_simu/axi_lite_led_simu_ooc.xdc
