// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        p_0_2_0_0_0250_7180_lcssa189,
        p_0_1_0_0_0248_7171_lcssa186,
        p_0_0_0_0_0246_7162_lcssa183,
        trunc_ln1,
        cmp236_2,
        cmp236_1,
        cmp236,
        icmp_ln749,
        cmp186_6,
        cmp186_5,
        cmp186_4,
        cmp186_3,
        cmp186_2,
        cmp186_1,
        sub183,
        cmp186,
        bytePlanes_plane01_din,
        bytePlanes_plane01_num_data_valid,
        bytePlanes_plane01_fifo_cap,
        bytePlanes_plane01_full_n,
        bytePlanes_plane01_write,
        p_0_2_0_0_0250_7179_out,
        p_0_2_0_0_0250_7179_out_ap_vld,
        p_0_1_0_0_0248_7170_out,
        p_0_1_0_0_0248_7170_out_ap_vld,
        p_0_0_0_0_0246_7161_out,
        p_0_0_0_0_0246_7161_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
input  [7:0] p_0_2_0_0_0250_7180_lcssa189;
input  [7:0] p_0_1_0_0_0248_7171_lcssa186;
input  [7:0] p_0_0_0_0_0246_7162_lcssa183;
input  [10:0] trunc_ln1;
input  [0:0] cmp236_2;
input  [0:0] cmp236_1;
input  [0:0] cmp236;
input  [0:0] icmp_ln749;
input  [0:0] cmp186_6;
input  [0:0] cmp186_5;
input  [0:0] cmp186_4;
input  [0:0] cmp186_3;
input  [0:0] cmp186_2;
input  [0:0] cmp186_1;
input  [10:0] sub183;
input  [0:0] cmp186;
output  [63:0] bytePlanes_plane01_din;
input  [9:0] bytePlanes_plane01_num_data_valid;
input  [9:0] bytePlanes_plane01_fifo_cap;
input   bytePlanes_plane01_full_n;
output   bytePlanes_plane01_write;
output  [7:0] p_0_2_0_0_0250_7179_out;
output   p_0_2_0_0_0250_7179_out_ap_vld;
output  [7:0] p_0_1_0_0_0248_7170_out;
output   p_0_1_0_0_0248_7170_out_ap_vld;
output  [7:0] p_0_0_0_0_0246_7161_out;
output   p_0_0_0_0_0246_7161_out_ap_vld;

reg ap_idle;
reg img_read;
reg[63:0] bytePlanes_plane01_din;
reg bytePlanes_plane01_write;
reg p_0_2_0_0_0250_7179_out_ap_vld;
reg p_0_1_0_0_0248_7170_out_ap_vld;
reg p_0_0_0_0_0246_7161_out_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] icmp_ln763_reg_840;
reg   [0:0] or_ln768_1_reg_876;
reg    ap_predicate_op68_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_subdone;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg   [0:0] or_ln768_6_reg_926;
reg    ap_predicate_op122_read_state8;
reg    ap_block_state8_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_subdone;
reg    img_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] or_ln768_reg_855;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln768_2_reg_900;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] or_ln768_3_reg_909;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] or_ln768_4_reg_918;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] or_ln768_5_reg_922;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln768_7_reg_930;
reg    bytePlanes_plane01_blk_n;
reg   [0:0] or_ln781_reg_859;
reg   [0:0] or_ln781_1_reg_863;
reg   [0:0] or_ln781_2_reg_867;
reg   [0:0] or_ln781_2_reg_867_pp0_iter1_reg;
reg   [7:0] p_0_2_0_0_0250_7178_reg_225;
reg   [7:0] p_0_1_0_0_0248_7169_reg_235;
reg   [7:0] p_0_0_0_0_0246_7160_reg_245;
reg   [7:0] p_0_2_0_0_0250_7177_reg_255;
reg   [7:0] p_0_1_0_0_0248_7168_reg_266;
reg   [7:0] p_0_0_0_0_0246_7159_reg_277;
reg   [7:0] p_0_2_0_0_0250_7176_reg_288;
reg   [7:0] p_0_2_0_0_0250_7175_reg_321;
reg   [7:0] p_0_1_0_0_0248_7166_reg_332;
reg   [7:0] p_0_0_0_0_0246_7157_reg_343;
reg   [7:0] p_0_2_0_0_0250_7174_reg_354;
reg   [7:0] p_0_1_0_0_0248_7165_reg_365;
reg   [7:0] p_0_0_0_0_0246_7156_reg_376;
reg   [7:0] p_0_2_0_0_0250_7173_reg_387;
reg   [7:0] p_0_1_0_0_0248_7164_reg_398;
reg    ap_predicate_op55_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state10_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg    ap_predicate_op88_read_state5;
reg    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_pp0_stage2_11001;
reg    ap_predicate_op101_read_state6;
reg    ap_predicate_op107_write_state6;
reg    ap_block_state6_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_11001;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op131_read_state9;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_predicate_op78_read_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_11001;
reg    ap_predicate_op113_read_state7;
reg    ap_block_state7_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_11001;
wire   [0:0] icmp_ln763_fu_565_p2;
reg   [0:0] icmp_ln763_reg_840_pp0_iter1_reg;
wire   [0:0] cmp184_fu_577_p2;
reg   [0:0] cmp184_reg_844;
wire   [0:0] or_ln768_fu_583_p2;
wire   [0:0] or_ln781_fu_589_p2;
wire   [0:0] or_ln781_1_fu_595_p2;
wire   [0:0] or_ln781_2_fu_601_p2;
wire   [7:0] trunc_ln769_fu_612_p1;
wire   [0:0] or_ln768_1_fu_616_p2;
wire   [7:0] trunc_ln769_3_fu_629_p1;
wire   [0:0] or_ln768_2_fu_633_p2;
wire   [7:0] trunc_ln769_6_fu_637_p1;
wire   [0:0] or_ln768_3_fu_641_p2;
wire   [7:0] trunc_ln769_9_fu_645_p1;
wire   [0:0] or_ln768_4_fu_649_p2;
wire   [0:0] or_ln768_5_fu_653_p2;
wire   [0:0] or_ln768_6_fu_657_p2;
wire   [0:0] or_ln768_7_fu_661_p2;
wire   [7:0] trunc_ln769_11_fu_665_p1;
wire   [7:0] trunc_ln769_14_fu_690_p1;
wire   [7:0] trunc_ln769_17_fu_694_p1;
reg    ap_block_pp0_stage7_11001;
wire   [7:0] trunc_ln769_20_fu_698_p1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7178_reg_225;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7169_reg_235;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7160_reg_245;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7177_reg_255;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7168_reg_266;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7159_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7176_reg_288;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7167_reg_299;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7158_reg_310;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7175_reg_321;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7166_reg_332;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7157_reg_343;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7174_reg_354;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7165_reg_365;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7156_reg_376;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7173_reg_387;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7173_reg_387;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7164_reg_398;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7164_reg_398;
reg   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7155_reg_409;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7155_reg_409;
wire   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7172_reg_420;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7172_reg_420;
wire   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7163_reg_430;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7163_reg_430;
wire   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7154_reg_440;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7154_reg_440;
reg   [7:0] ap_phi_mux_p_0_2_0_0_0250_7180_phi_fu_453_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7180_reg_450;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7180_reg_450;
reg   [7:0] ap_phi_mux_p_0_1_0_0_0248_7171_phi_fu_463_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7171_reg_460;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7171_reg_460;
reg   [7:0] ap_phi_mux_p_0_0_0_0_0246_7162_phi_fu_473_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7162_reg_470;
reg   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7162_reg_470;
reg   [9:0] x_1_fu_100;
wire   [9:0] x_3_fu_571_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_x;
reg   [7:0] p_0_0_0_0_0246_7161_fu_104;
reg   [7:0] p_0_1_0_0_0248_7170_fu_108;
reg   [7:0] p_0_2_0_0_0250_7179_fu_112;
wire   [63:0] p_s_fu_669_p9;
reg    ap_block_pp0_stage5_01001;
wire   [63:0] p_2_fu_702_p9;
reg    ap_block_pp0_stage0_01001;
wire   [63:0] p_0_fu_723_p9;
reg    ap_block_pp0_stage1_01001;
wire   [10:0] zext_ln763_fu_561_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_827;
reg    ap_condition_830;
reg    ap_condition_833;
reg    ap_condition_836;
reg    ap_condition_839;
reg    ap_condition_842;
reg    ap_condition_846;
reg    ap_condition_850;
reg    ap_condition_853;
reg    ap_condition_856;
reg    ap_condition_458;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_830)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7156_reg_376 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7157_reg_343;
        end else if ((1'b1 == ap_condition_827)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7156_reg_376 <= trunc_ln769_11_fu_665_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_836)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7157_reg_343 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7158_reg_310;
        end else if ((1'b1 == ap_condition_833)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7157_reg_343 <= trunc_ln769_9_fu_645_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_842)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7158_reg_310 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7159_reg_277;
        end else if ((1'b1 == ap_condition_839)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7158_reg_310 <= trunc_ln769_6_fu_637_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_850)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7159_reg_277 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7160_reg_245;
        end else if ((1'b1 == ap_condition_846)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7159_reg_277 <= trunc_ln769_3_fu_629_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_856)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7160_reg_245 <= p_0_0_0_0_0246_7161_fu_104;
        end else if ((1'b1 == ap_condition_853)) begin
            ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7160_reg_245 <= trunc_ln769_fu_612_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_830)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7165_reg_365 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7166_reg_332;
        end else if ((1'b1 == ap_condition_827)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7165_reg_365 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_836)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7166_reg_332 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7167_reg_299;
        end else if ((1'b1 == ap_condition_833)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7166_reg_332 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_842)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7167_reg_299 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7168_reg_266;
        end else if ((1'b1 == ap_condition_839)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7167_reg_299 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_850)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7168_reg_266 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7169_reg_235;
        end else if ((1'b1 == ap_condition_846)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7168_reg_266 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_856)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7169_reg_235 <= p_0_1_0_0_0248_7170_fu_108;
        end else if ((1'b1 == ap_condition_853)) begin
            ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7169_reg_235 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_830)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7174_reg_354 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7175_reg_321;
        end else if ((1'b1 == ap_condition_827)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7174_reg_354 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_836)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7175_reg_321 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7176_reg_288;
        end else if ((1'b1 == ap_condition_833)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7175_reg_321 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_842)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7176_reg_288 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7177_reg_255;
        end else if ((1'b1 == ap_condition_839)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7176_reg_288 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_850)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7177_reg_255 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7178_reg_225;
        end else if ((1'b1 == ap_condition_846)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7177_reg_255 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_856)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7178_reg_225 <= p_0_2_0_0_0250_7179_fu_112;
        end else if ((1'b1 == ap_condition_853)) begin
            ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7178_reg_225 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln768_6_reg_926 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7154_reg_440 <= ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7155_reg_409;
    end else if (((or_ln768_6_reg_926 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7154_reg_440 <= trunc_ln769_17_fu_694_p1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7154_reg_440 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7154_reg_440;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_458)) begin
        if (((icmp_ln763_reg_840 == 1'd1) & (or_ln768_5_reg_922 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7155_reg_409 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7156_reg_376;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7155_reg_409 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7155_reg_409;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln768_7_reg_930 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7162_reg_470 <= trunc_ln769_20_fu_698_p1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7162_reg_470 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7162_reg_470;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln768_6_reg_926 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7163_reg_430 <= ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7164_reg_398;
    end else if (((or_ln768_6_reg_926 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7163_reg_430 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7163_reg_430 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7163_reg_430;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_458)) begin
        if (((icmp_ln763_reg_840 == 1'd1) & (or_ln768_5_reg_922 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7164_reg_398 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7165_reg_365;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7164_reg_398 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7164_reg_398;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln768_7_reg_930 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7171_reg_460 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7171_reg_460 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7171_reg_460;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln768_6_reg_926 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7172_reg_420 <= ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7173_reg_387;
    end else if (((or_ln768_6_reg_926 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7172_reg_420 <= {{img_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7172_reg_420 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7172_reg_420;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_458)) begin
        if (((icmp_ln763_reg_840 == 1'd1) & (or_ln768_5_reg_922 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7173_reg_387 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7174_reg_354;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7173_reg_387 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7173_reg_387;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln768_7_reg_930 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7180_reg_450 <= {{img_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7180_reg_450 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7180_reg_450;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_0246_7161_fu_104 <= p_0_0_0_0_0246_7162_lcssa183;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_0_0_0_0_0246_7161_fu_104 <= ap_phi_mux_p_0_0_0_0_0246_7162_phi_fu_473_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_0248_7170_fu_108 <= p_0_1_0_0_0248_7171_lcssa186;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_0_1_0_0_0248_7170_fu_108 <= ap_phi_mux_p_0_1_0_0_0248_7171_phi_fu_463_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_0250_7179_fu_112 <= p_0_2_0_0_0250_7180_lcssa189;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_0_2_0_0_0250_7179_fu_112 <= ap_phi_mux_p_0_2_0_0_0250_7180_phi_fu_453_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln763_fu_565_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_1_fu_100 <= x_3_fu_571_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_1_fu_100 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln768_5_reg_922 == 1'd1))) begin
        ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7155_reg_409 <= trunc_ln769_14_fu_690_p1;
        ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7164_reg_398 <= {{img_dout[15:8]}};
        ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7173_reg_387 <= {{img_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln763_fu_565_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp184_reg_844 <= cmp184_fu_577_p2;
        or_ln768_reg_855 <= or_ln768_fu_583_p2;
        or_ln781_1_reg_863 <= or_ln781_1_fu_595_p2;
        or_ln781_2_reg_867 <= or_ln781_2_fu_601_p2;
        or_ln781_reg_859 <= or_ln781_fu_589_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln763_reg_840 <= icmp_ln763_fu_565_p2;
        icmp_ln763_reg_840_pp0_iter1_reg <= icmp_ln763_reg_840;
        or_ln781_2_reg_867_pp0_iter1_reg <= or_ln781_2_reg_867;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln763_reg_840 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln768_1_reg_876 <= or_ln768_1_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln763_reg_840 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln768_2_reg_900 <= or_ln768_2_fu_633_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln763_reg_840 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_ln768_3_reg_909 <= or_ln768_3_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln763_reg_840 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        or_ln768_4_reg_918 <= or_ln768_4_fu_649_p2;
        or_ln768_5_reg_922 <= or_ln768_5_fu_653_p2;
        or_ln768_6_reg_926 <= or_ln768_6_fu_657_p2;
        or_ln768_7_reg_930 <= or_ln768_7_fu_661_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        p_0_0_0_0_0246_7156_reg_376 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7156_reg_376;
        p_0_1_0_0_0248_7165_reg_365 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7165_reg_365;
        p_0_2_0_0_0250_7174_reg_354 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7174_reg_354;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        p_0_0_0_0_0246_7157_reg_343 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7157_reg_343;
        p_0_1_0_0_0248_7166_reg_332 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7166_reg_332;
        p_0_2_0_0_0250_7175_reg_321 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7175_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        p_0_0_0_0_0246_7159_reg_277 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7159_reg_277;
        p_0_1_0_0_0248_7168_reg_266 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7168_reg_266;
        p_0_2_0_0_0250_7177_reg_255 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7177_reg_255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_0_0_0_0_0246_7160_reg_245 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7160_reg_245;
        p_0_1_0_0_0248_7169_reg_235 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7169_reg_235;
        p_0_2_0_0_0250_7178_reg_225 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7178_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_0248_7164_reg_398 <= ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7164_reg_398;
        p_0_2_0_0_0250_7173_reg_387 <= ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7173_reg_387;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        p_0_2_0_0_0250_7176_reg_288 <= ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7176_reg_288;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (icmp_ln763_reg_840 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln763_reg_840_pp0_iter1_reg == 1'd1) & (or_ln768_7_reg_930 == 1'd0))) begin
        ap_phi_mux_p_0_0_0_0_0246_7162_phi_fu_473_p4 = ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7154_reg_440;
    end else begin
        ap_phi_mux_p_0_0_0_0_0246_7162_phi_fu_473_p4 = ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7162_reg_470;
    end
end

always @ (*) begin
    if (((icmp_ln763_reg_840_pp0_iter1_reg == 1'd1) & (or_ln768_7_reg_930 == 1'd0))) begin
        ap_phi_mux_p_0_1_0_0_0248_7171_phi_fu_463_p4 = ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7163_reg_430;
    end else begin
        ap_phi_mux_p_0_1_0_0_0248_7171_phi_fu_463_p4 = ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7171_reg_460;
    end
end

always @ (*) begin
    if (((icmp_ln763_reg_840_pp0_iter1_reg == 1'd1) & (or_ln768_7_reg_930 == 1'd0))) begin
        ap_phi_mux_p_0_2_0_0_0250_7180_phi_fu_453_p4 = ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7172_reg_420;
    end else begin
        ap_phi_mux_p_0_2_0_0_0250_7180_phi_fu_453_p4 = ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7180_reg_450;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x = 10'd0;
    end else begin
        ap_sig_allocacmp_x = x_1_fu_100;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_1_reg_863 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln781_reg_859 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        bytePlanes_plane01_blk_n = bytePlanes_plane01_full_n;
    end else begin
        bytePlanes_plane01_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane01_din = p_0_fu_723_p9;
    end else if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_1_reg_863 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bytePlanes_plane01_din = p_2_fu_702_p9;
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op107_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        bytePlanes_plane01_din = p_s_fu_669_p9;
    end else begin
        bytePlanes_plane01_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_1_reg_863 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op107_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        bytePlanes_plane01_write = 1'b1;
    end else begin
        bytePlanes_plane01_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op122_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln768_7_reg_930 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln768_5_reg_922 == 1'd1)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln768_4_reg_918 == 1'd1)) | ((1'b0 == ap_block_pp0_stage4) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln768_3_reg_909 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln768_2_reg_900 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2) & (ap_predicate_op68_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln763_reg_840 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln768_reg_855 == 1'd1)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op122_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op113_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op78_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op131_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op101_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op68_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op88_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op55_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln763_reg_840 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_0_0_0_0_0246_7161_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_0246_7161_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln763_reg_840 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_0_1_0_0_0248_7170_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_0248_7170_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln763_reg_840 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_0_2_0_0_0250_7179_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_0250_7179_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op131_read_state9 == 1'b1)) | ((or_ln781_1_reg_863 == 1'd1) & (bytePlanes_plane01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op131_read_state9 == 1'b1)) | ((or_ln781_1_reg_863 == 1'd1) & (bytePlanes_plane01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op131_read_state9 == 1'b1)) | ((or_ln781_1_reg_863 == 1'd1) & (bytePlanes_plane01_full_n == 1'b0))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((img_empty_n == 1'b0) & (ap_predicate_op55_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (bytePlanes_plane01_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((img_empty_n == 1'b0) & (ap_predicate_op55_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (bytePlanes_plane01_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((img_empty_n == 1'b0) & (ap_predicate_op55_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (bytePlanes_plane01_full_n == 1'b0)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_predicate_op68_read_state3 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_predicate_op68_read_state3 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((img_empty_n == 1'b0) & (ap_predicate_op78_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((img_empty_n == 1'b0) & (ap_predicate_op78_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((img_empty_n == 1'b0) & (ap_predicate_op88_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((img_empty_n == 1'b0) & (ap_predicate_op88_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op101_read_state6 == 1'b1)) | ((ap_predicate_op107_write_state6 == 1'b1) & (bytePlanes_plane01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op101_read_state6 == 1'b1)) | ((ap_predicate_op107_write_state6 == 1'b1) & (bytePlanes_plane01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op101_read_state6 == 1'b1)) | ((ap_predicate_op107_write_state6 == 1'b1) & (bytePlanes_plane01_full_n == 1'b0))));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((img_empty_n == 1'b0) & (ap_predicate_op113_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((img_empty_n == 1'b0) & (ap_predicate_op113_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_predicate_op122_read_state8 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_predicate_op122_read_state8 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter1 = ((or_ln781_2_reg_867_pp0_iter1_reg == 1'd1) & (bytePlanes_plane01_full_n == 1'b0));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op55_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((ap_predicate_op68_read_state3 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op78_read_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op88_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0 = (((img_empty_n == 1'b0) & (ap_predicate_op101_read_state6 == 1'b1)) | ((ap_predicate_op107_write_state6 == 1'b1) & (bytePlanes_plane01_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op113_read_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0 = ((ap_predicate_op122_read_state8 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (((img_empty_n == 1'b0) & (ap_predicate_op131_read_state9 == 1'b1)) | ((or_ln781_1_reg_863 == 1'd1) & (bytePlanes_plane01_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_458 = ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

always @ (*) begin
    ap_condition_827 = ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln768_4_reg_918 == 1'd1));
end

always @ (*) begin
    ap_condition_830 = ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln768_4_reg_918 == 1'd0));
end

always @ (*) begin
    ap_condition_833 = ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln768_3_reg_909 == 1'd1));
end

always @ (*) begin
    ap_condition_836 = ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln768_3_reg_909 == 1'd0));
end

always @ (*) begin
    ap_condition_839 = ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln768_2_reg_900 == 1'd1));
end

always @ (*) begin
    ap_condition_842 = ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln768_2_reg_900 == 1'd0));
end

always @ (*) begin
    ap_condition_846 = ((1'b0 == ap_block_pp0_stage2_11001) & (or_ln768_1_reg_876 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_850 = ((1'b0 == ap_block_pp0_stage3_11001) & (or_ln768_1_reg_876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_853 = ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln768_reg_855 == 1'd1));
end

always @ (*) begin
    ap_condition_856 = ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln768_reg_855 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7154_reg_440 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7162_reg_470 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7163_reg_430 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7171_reg_460 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7172_reg_420 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_2_0_0_0250_7180_reg_450 = 'bx;

always @ (*) begin
    ap_predicate_op101_read_state6 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln768_4_reg_918 == 1'd1));
end

always @ (*) begin
    ap_predicate_op107_write_state6 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln781_reg_859 == 1'd1));
end

always @ (*) begin
    ap_predicate_op113_read_state7 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln768_5_reg_922 == 1'd1));
end

always @ (*) begin
    ap_predicate_op122_read_state8 = ((or_ln768_6_reg_926 == 1'd1) & (icmp_ln763_reg_840 == 1'd1));
end

always @ (*) begin
    ap_predicate_op131_read_state9 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln768_7_reg_930 == 1'd1));
end

always @ (*) begin
    ap_predicate_op55_read_state2 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln768_reg_855 == 1'd1));
end

always @ (*) begin
    ap_predicate_op68_read_state3 = ((or_ln768_1_reg_876 == 1'd1) & (icmp_ln763_reg_840 == 1'd1));
end

always @ (*) begin
    ap_predicate_op78_read_state4 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln768_2_reg_900 == 1'd1));
end

always @ (*) begin
    ap_predicate_op88_read_state5 = ((icmp_ln763_reg_840 == 1'd1) & (or_ln768_3_reg_909 == 1'd1));
end

assign cmp184_fu_577_p2 = (($signed(zext_ln763_fu_561_p1) < $signed(sub183)) ? 1'b1 : 1'b0);

assign icmp_ln763_fu_565_p2 = (($signed(zext_ln763_fu_561_p1) < $signed(trunc_ln1)) ? 1'b1 : 1'b0);

assign or_ln768_1_fu_616_p2 = (cmp186_1 | cmp184_reg_844);

assign or_ln768_2_fu_633_p2 = (cmp186_2 | cmp184_reg_844);

assign or_ln768_3_fu_641_p2 = (cmp186_3 | cmp184_reg_844);

assign or_ln768_4_fu_649_p2 = (cmp186_4 | cmp184_reg_844);

assign or_ln768_5_fu_653_p2 = (cmp186_5 | cmp184_reg_844);

assign or_ln768_6_fu_657_p2 = (cmp186_6 | cmp184_reg_844);

assign or_ln768_7_fu_661_p2 = (icmp_ln749 | cmp184_reg_844);

assign or_ln768_fu_583_p2 = (cmp186 | cmp184_fu_577_p2);

assign or_ln781_1_fu_595_p2 = (cmp236_1 | cmp184_fu_577_p2);

assign or_ln781_2_fu_601_p2 = (cmp236_2 | cmp184_fu_577_p2);

assign or_ln781_fu_589_p2 = (cmp236 | cmp184_fu_577_p2);

assign p_0_0_0_0_0246_7161_out = p_0_0_0_0_0246_7161_fu_104;

assign p_0_1_0_0_0248_7170_out = p_0_1_0_0_0248_7170_fu_108;

assign p_0_2_0_0_0250_7179_out = p_0_2_0_0_0250_7179_fu_112;

assign p_0_fu_723_p9 = {{{{{{{{ap_phi_mux_p_0_2_0_0_0250_7180_phi_fu_453_p4}, {ap_phi_mux_p_0_1_0_0_0248_7171_phi_fu_463_p4}}, {ap_phi_mux_p_0_0_0_0_0246_7162_phi_fu_473_p4}}, {ap_phi_reg_pp0_iter1_p_0_2_0_0_0250_7172_reg_420}}, {ap_phi_reg_pp0_iter1_p_0_1_0_0_0248_7163_reg_430}}, {ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7154_reg_440}}, {p_0_2_0_0_0250_7173_reg_387}}, {p_0_1_0_0_0248_7164_reg_398}};

assign p_2_fu_702_p9 = {{{{{{{{ap_phi_reg_pp0_iter1_p_0_0_0_0_0246_7155_reg_409}, {p_0_2_0_0_0250_7174_reg_354}}, {p_0_1_0_0_0248_7165_reg_365}}, {p_0_0_0_0_0246_7156_reg_376}}, {p_0_2_0_0_0250_7175_reg_321}}, {p_0_1_0_0_0248_7166_reg_332}}, {p_0_0_0_0_0246_7157_reg_343}}, {p_0_2_0_0_0250_7176_reg_288}};

assign p_s_fu_669_p9 = {{{{{{{{ap_phi_reg_pp0_iter0_p_0_1_0_0_0248_7167_reg_299}, {ap_phi_reg_pp0_iter0_p_0_0_0_0_0246_7158_reg_310}}, {p_0_2_0_0_0250_7177_reg_255}}, {p_0_1_0_0_0248_7168_reg_266}}, {p_0_0_0_0_0246_7159_reg_277}}, {p_0_2_0_0_0250_7178_reg_225}}, {p_0_1_0_0_0248_7169_reg_235}}, {p_0_0_0_0_0246_7160_reg_245}};

assign trunc_ln769_11_fu_665_p1 = img_dout[7:0];

assign trunc_ln769_14_fu_690_p1 = img_dout[7:0];

assign trunc_ln769_17_fu_694_p1 = img_dout[7:0];

assign trunc_ln769_20_fu_698_p1 = img_dout[7:0];

assign trunc_ln769_3_fu_629_p1 = img_dout[7:0];

assign trunc_ln769_6_fu_637_p1 = img_dout[7:0];

assign trunc_ln769_9_fu_645_p1 = img_dout[7:0];

assign trunc_ln769_fu_612_p1 = img_dout[7:0];

assign x_3_fu_571_p2 = (ap_sig_allocacmp_x + 10'd1);

assign zext_ln763_fu_561_p1 = ap_sig_allocacmp_x;

endmodule //kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_4
