// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_eab1_vsc_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_895_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutYUV_dout,
        OutYUV_num_data_valid,
        OutYUV_fifo_cap,
        OutYUV_empty_n,
        OutYUV_read,
        m_axis_video_TREADY,
        sof,
        cols,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        ColorMode_load,
        sub
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] OutYUV_dout;
input  [4:0] OutYUV_num_data_valid;
input  [4:0] OutYUV_fifo_cap;
input   OutYUV_empty_n;
output   OutYUV_read;
input   m_axis_video_TREADY;
input  [0:0] sof;
input  [10:0] cols;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [7:0] ColorMode_load;
input  [11:0] sub;

reg ap_idle;
reg OutYUV_read;
reg m_axis_video_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln895_reg_395;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln895_fu_223_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m_axis_video_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    OutYUV_blk_n;
reg   [0:0] tmp_user_V_reg_165;
wire   [7:0] ColorMode_load_read_reg_386;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_last_V_fu_235_p2;
reg   [0:0] tmp_last_V_reg_399;
wire    ap_loop_init;
reg   [8:0] ap_phi_mux_p_Val2_s_phi_fu_180_p6;
wire   [8:0] p_Result_10_fu_288_p3;
wire   [8:0] ap_phi_reg_pp0_iter1_p_Val2_s_reg_177;
wire   [8:0] p_Result_9_fu_270_p3;
wire   [8:0] p_Result_8_fu_279_p3;
reg   [23:0] ap_phi_mux_p_Val2_6_phi_fu_191_p6;
wire   [23:0] p_Result_12_fu_327_p5;
wire   [23:0] ap_phi_reg_pp0_iter1_p_Val2_6_reg_188;
wire   [23:0] p_Result_7_fu_301_p5;
wire   [23:0] p_Result_11_fu_314_p5;
reg   [23:0] ap_phi_mux_axi_data_V_12_phi_fu_202_p6;
wire   [23:0] p_Result_14_fu_366_p5;
wire   [23:0] ap_phi_reg_pp0_iter1_axi_data_V_12_reg_199;
wire   [23:0] p_Result_s_fu_340_p5;
wire   [23:0] p_Result_13_fu_353_p5;
reg   [10:0] j_fu_102;
wire   [10:0] j_2_fu_229_p2;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] zext_ln895_fu_219_p1;
wire   [7:0] pix_rgb_V_fu_246_p1;
wire   [7:0] pix_444_V_1_fu_250_p4;
wire  signed [23:0] sext_ln844_fu_297_p1;
wire   [7:0] pix_444_V_fu_260_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_283;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

bd_eab1_vsc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln895_fu_223_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_102 <= j_2_fu_229_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_102 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            tmp_user_V_reg_165 <= sof;
        end else if ((1'b1 == ap_condition_283)) begin
            tmp_user_V_reg_165 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln895_reg_395 <= icmp_ln895_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln895_fu_223_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_last_V_reg_399 <= tmp_last_V_fu_235_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln895_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutYUV_blk_n = OutYUV_empty_n;
    end else begin
        OutYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln895_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutYUV_read = 1'b1;
    end else begin
        OutYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln895_fu_223_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln895_reg_395 == 1'd0)) begin
        if ((8'd0 == ColorMode_load_read_reg_386)) begin
            ap_phi_mux_axi_data_V_12_phi_fu_202_p6 = p_Result_13_fu_353_p5;
        end else if ((8'd1 == ColorMode_load_read_reg_386)) begin
            ap_phi_mux_axi_data_V_12_phi_fu_202_p6 = p_Result_s_fu_340_p5;
        end else if ((~(8'd1 == ColorMode_load_read_reg_386) & ~(8'd0 == ColorMode_load_read_reg_386))) begin
            ap_phi_mux_axi_data_V_12_phi_fu_202_p6 = p_Result_14_fu_366_p5;
        end else begin
            ap_phi_mux_axi_data_V_12_phi_fu_202_p6 = ap_phi_reg_pp0_iter1_axi_data_V_12_reg_199;
        end
    end else begin
        ap_phi_mux_axi_data_V_12_phi_fu_202_p6 = ap_phi_reg_pp0_iter1_axi_data_V_12_reg_199;
    end
end

always @ (*) begin
    if ((icmp_ln895_reg_395 == 1'd0)) begin
        if ((8'd0 == ColorMode_load_read_reg_386)) begin
            ap_phi_mux_p_Val2_6_phi_fu_191_p6 = p_Result_11_fu_314_p5;
        end else if ((8'd1 == ColorMode_load_read_reg_386)) begin
            ap_phi_mux_p_Val2_6_phi_fu_191_p6 = p_Result_7_fu_301_p5;
        end else if ((~(8'd1 == ColorMode_load_read_reg_386) & ~(8'd0 == ColorMode_load_read_reg_386))) begin
            ap_phi_mux_p_Val2_6_phi_fu_191_p6 = p_Result_12_fu_327_p5;
        end else begin
            ap_phi_mux_p_Val2_6_phi_fu_191_p6 = ap_phi_reg_pp0_iter1_p_Val2_6_reg_188;
        end
    end else begin
        ap_phi_mux_p_Val2_6_phi_fu_191_p6 = ap_phi_reg_pp0_iter1_p_Val2_6_reg_188;
    end
end

always @ (*) begin
    if ((icmp_ln895_reg_395 == 1'd0)) begin
        if ((8'd0 == ColorMode_load_read_reg_386)) begin
            ap_phi_mux_p_Val2_s_phi_fu_180_p6 = p_Result_8_fu_279_p3;
        end else if ((8'd1 == ColorMode_load_read_reg_386)) begin
            ap_phi_mux_p_Val2_s_phi_fu_180_p6 = p_Result_9_fu_270_p3;
        end else if ((~(8'd1 == ColorMode_load_read_reg_386) & ~(8'd0 == ColorMode_load_read_reg_386))) begin
            ap_phi_mux_p_Val2_s_phi_fu_180_p6 = p_Result_10_fu_288_p3;
        end else begin
            ap_phi_mux_p_Val2_s_phi_fu_180_p6 = ap_phi_reg_pp0_iter1_p_Val2_s_reg_177;
        end
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_180_p6 = ap_phi_reg_pp0_iter1_p_Val2_s_reg_177;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln895_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln895_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ColorMode_load_read_reg_386 = ColorMode_load;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((m_axis_video_TREADY == 1'b0) & (icmp_ln895_reg_395 == 1'd0)) | ((icmp_ln895_reg_395 == 1'd0) & (1'b0 == OutYUV_empty_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((m_axis_video_TREADY == 1'b0) & (icmp_ln895_reg_395 == 1'd0)) | ((icmp_ln895_reg_395 == 1'd0) & (1'b0 == OutYUV_empty_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((m_axis_video_TREADY == 1'b0) & (icmp_ln895_reg_395 == 1'd0)) | ((icmp_ln895_reg_395 == 1'd0) & (1'b0 == OutYUV_empty_n))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((m_axis_video_TREADY == 1'b0) & (icmp_ln895_reg_395 == 1'd0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((m_axis_video_TREADY == 1'b0) & (icmp_ln895_reg_395 == 1'd0)) | ((icmp_ln895_reg_395 == 1'd0) & (1'b0 == OutYUV_empty_n)));
end

always @ (*) begin
    ap_condition_283 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln895_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_axi_data_V_12_reg_199 = 'bx;

assign ap_phi_reg_pp0_iter1_p_Val2_6_reg_188 = 'bx;

assign ap_phi_reg_pp0_iter1_p_Val2_s_reg_177 = 'bx;

assign icmp_ln895_fu_223_p2 = ((ap_sig_allocacmp_j_1 == cols) ? 1'b1 : 1'b0);

assign j_2_fu_229_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign m_axis_video_TDATA = ap_phi_mux_axi_data_V_12_phi_fu_202_p6;

assign m_axis_video_TDEST = 1'd0;

assign m_axis_video_TID = 1'd0;

assign m_axis_video_TKEEP = 3'd7;

assign m_axis_video_TLAST = tmp_last_V_reg_399;

assign m_axis_video_TSTRB = 3'd0;

assign m_axis_video_TUSER = tmp_user_V_reg_165;

assign p_Result_10_fu_288_p3 = {{1'd1}, {pix_rgb_V_fu_246_p1}};

assign p_Result_11_fu_314_p5 = {{sext_ln844_fu_297_p1[23:16]}, {pix_444_V_fu_260_p4}, {sext_ln844_fu_297_p1[7:0]}};

assign p_Result_12_fu_327_p5 = {{sext_ln844_fu_297_p1[23:16]}, {pix_444_V_1_fu_250_p4}, {sext_ln844_fu_297_p1[7:0]}};

assign p_Result_13_fu_353_p5 = {{pix_rgb_V_fu_246_p1}, {ap_phi_mux_p_Val2_6_phi_fu_191_p6[15:0]}};

assign p_Result_14_fu_366_p5 = {{pix_444_V_fu_260_p4}, {ap_phi_mux_p_Val2_6_phi_fu_191_p6[15:0]}};

assign p_Result_7_fu_301_p5 = {{sext_ln844_fu_297_p1[23:16]}, {pix_444_V_1_fu_250_p4}, {sext_ln844_fu_297_p1[7:0]}};

assign p_Result_8_fu_279_p3 = {{1'd1}, {pix_444_V_1_fu_250_p4}};

assign p_Result_9_fu_270_p3 = {{1'd1}, {pix_rgb_V_fu_246_p1}};

assign p_Result_s_fu_340_p5 = {{pix_444_V_fu_260_p4}, {ap_phi_mux_p_Val2_6_phi_fu_191_p6[15:0]}};

assign pix_444_V_1_fu_250_p4 = {{OutYUV_dout[15:8]}};

assign pix_444_V_fu_260_p4 = {{OutYUV_dout[23:16]}};

assign pix_rgb_V_fu_246_p1 = OutYUV_dout[7:0];

assign sext_ln844_fu_297_p1 = $signed(ap_phi_mux_p_Val2_s_phi_fu_180_p6);

assign tmp_last_V_fu_235_p2 = ((zext_ln895_fu_219_p1 == sub) ? 1'b1 : 1'b0);

assign zext_ln895_fu_219_p1 = ap_sig_allocacmp_j_1;

endmodule //bd_eab1_vsc_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_895_2
