# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.srcs/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/bd_3be0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0 || ORIG_REF_NAME==bd_3be0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_3be0_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_xbar_0 || ORIG_REF_NAME==bd_3be0_xbar_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_3be0_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_r_sync_0 || ORIG_REF_NAME==bd_3be0_r_sync_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_3be0_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_rx_0 || ORIG_REF_NAME==bd_3be0_rx_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_3be0_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_phy_0 || ORIG_REF_NAME==bd_3be0_phy_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_4/bd_3be0_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_vfb_0_0 || ORIG_REF_NAME==bd_3be0_vfb_0_0} -quiet] -quiet

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/bd_3be0_ooc.xdc

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.srcs/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/bd_3be0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0 || ORIG_REF_NAME==bd_3be0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_3be0_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_xbar_0 || ORIG_REF_NAME==bd_3be0_xbar_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_3be0_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_r_sync_0 || ORIG_REF_NAME==bd_3be0_r_sync_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_3be0_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_rx_0 || ORIG_REF_NAME==bd_3be0_rx_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_3be0_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_phy_0 || ORIG_REF_NAME==bd_3be0_phy_0} -quiet] -quiet

# IP: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_4/bd_3be0_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3be0_vfb_0_0 || ORIG_REF_NAME==bd_3be0_vfb_0_0} -quiet] -quiet

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/bd_0/bd_3be0_ooc.xdc

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
