-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_eab1_vsc_0_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    SrcYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    SrcYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    SrcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    SrcYUV_empty_n : IN STD_LOGIC;
    SrcYUV_read : OUT STD_LOGIC;
    SrcYUV422_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    SrcYUV422_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    SrcYUV422_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    SrcYUV422_full_n : IN STD_LOGIC;
    SrcYUV422_write : OUT STD_LOGIC;
    loopWidth : IN STD_LOGIC_VECTOR (10 downto 0);
    sel_tmp1 : IN STD_LOGIC_VECTOR (0 downto 0);
    sel_tmp4 : IN STD_LOGIC_VECTOR (0 downto 0);
    sel_tmp6 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp287 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp391 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp104 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp36 : IN STD_LOGIC_VECTOR (0 downto 0);
    linebuf_y_val_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_y_val_V_ce0 : OUT STD_LOGIC;
    linebuf_y_val_V_we0 : OUT STD_LOGIC;
    linebuf_y_val_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf_y_val_V_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_y_val_V_ce1 : OUT STD_LOGIC;
    linebuf_y_val_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf_y_val_V_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_y_val_V_1_ce0 : OUT STD_LOGIC;
    linebuf_y_val_V_1_we0 : OUT STD_LOGIC;
    linebuf_y_val_V_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf_y_val_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf_c_val_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_c_val_V_ce0 : OUT STD_LOGIC;
    linebuf_c_val_V_we0 : OUT STD_LOGIC;
    linebuf_c_val_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf_c_val_V_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_c_val_V_ce1 : OUT STD_LOGIC;
    linebuf_c_val_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    linebuf_c_val_V_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_c_val_V_1_ce0 : OUT STD_LOGIC;
    linebuf_c_val_V_1_we0 : OUT STD_LOGIC;
    linebuf_c_val_V_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linebuf_c_val_V_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_c_val_V_1_ce1 : OUT STD_LOGIC;
    linebuf_c_val_V_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    spec_select : IN STD_LOGIC_VECTOR (0 downto 0);
    linebuf_c_val_V_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    linebuf_c_val_V_2_ce0 : OUT STD_LOGIC;
    linebuf_c_val_V_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    icmp_ln995 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_0_1_0_0_0878_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_0878_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_0878_out_o_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0_0423876_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0423876_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0423876_out_o_ap_vld : OUT STD_LOGIC;
    p_0_2_0_0_0874_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_2_0_0_0874_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_2_0_0_0874_out_o_ap_vld : OUT STD_LOGIC;
    p_0_1_0_0_0872_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_0872_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_0872_out_o_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0_0423870_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0423870_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0423870_out_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of bd_eab1_vsc_0_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln1012_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp36_read_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op36_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op82_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_predicate_op103_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1012_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal SrcYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal SrcYUV422_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal spec_select_read_reg_563 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_read_reg_587 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_read_reg_592 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_x_reg_602 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1012_reg_607_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1012_reg_607_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_y_val_V_addr_reg_611 : STD_LOGIC_VECTOR (10 downto 0);
    signal linebuf_y_val_V_1_addr_reg_617 : STD_LOGIC_VECTOR (10 downto 0);
    signal linebuf_c_val_V_addr_reg_622 : STD_LOGIC_VECTOR (10 downto 0);
    signal linebuf_c_val_V_1_addr_reg_628 : STD_LOGIC_VECTOR (10 downto 0);
    signal LineBufVal_V_14_reg_639 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_fu_401_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_reg_649 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1495_2_fu_416_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1495_2_reg_661 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_21_fu_420_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_21_reg_666 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_p_0_0_0_0_0404883_reg_265 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_rhs_2_phi_fu_278_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_rhs_2_reg_275 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_lhs_reg_286 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_lhs_reg_286 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_lhs_reg_286 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_lhs_reg_286 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1012_fu_320_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1022_fu_328_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fu_112 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1012_fu_309_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_out_x : STD_LOGIC_VECTOR (10 downto 0);
    signal p_0_fu_438_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1184_fu_547_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ret_V_20_fu_452_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1495_3_fu_467_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1495_fu_459_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1495_2_fu_470_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1495_1_fu_463_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1495_1_fu_476_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1494_fu_449_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1495_3_fu_492_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_fu_498_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln186_1_fu_503_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln3_fu_482_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp2_fu_513_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp5_fu_519_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0406889894_fu_526_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_4_fu_533_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_539_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_47 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_enable_operation_58 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_enable_operation_60 : BOOLEAN;
    signal ap_enable_operation_62 : BOOLEAN;
    signal ap_predicate_op59_load_state3 : BOOLEAN;
    signal ap_enable_operation_59 : BOOLEAN;
    signal ap_predicate_op84_load_state4 : BOOLEAN;
    signal ap_enable_operation_84 : BOOLEAN;
    signal ap_enable_state4_pp0_iter3_stage0 : BOOLEAN;
    signal ap_enable_operation_50 : BOOLEAN;
    signal ap_enable_operation_63 : BOOLEAN;
    signal ap_predicate_op67_store_state3 : BOOLEAN;
    signal ap_enable_operation_67 : BOOLEAN;
    signal ap_enable_operation_52 : BOOLEAN;
    signal ap_enable_operation_64 : BOOLEAN;
    signal ap_predicate_op71_store_state3 : BOOLEAN;
    signal ap_enable_operation_71 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_eab1_vsc_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component bd_eab1_vsc_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter3_lhs_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select_read_reg_563 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter3_lhs_reg_286 <= linebuf_c_val_V_2_q0;
                elsif (((icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_lhs_reg_286 <= linebuf_c_val_V_1_q1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_lhs_reg_286 <= ap_phi_reg_pp0_iter2_lhs_reg_286;
                end if;
            end if; 
        end if;
    end process;

    x_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1012_fu_303_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_112 <= add_ln1012_fu_309_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_112 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0))) then
                LineBufVal_V_14_reg_639 <= linebuf_y_val_V_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln1012_reg_607 <= icmp_ln1012_fu_303_p2;
                icmp_ln1012_reg_607_pp0_iter1_reg <= icmp_ln1012_reg_607;
                out_x_reg_602 <= ap_sig_allocacmp_out_x;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_lhs_reg_286 <= ap_phi_reg_pp0_iter0_lhs_reg_286;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_lhs_reg_286 <= ap_phi_reg_pp0_iter1_lhs_reg_286;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln1012_reg_607_pp0_iter2_reg <= icmp_ln1012_reg_607_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                linebuf_c_val_V_1_addr_reg_628 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);
                linebuf_c_val_V_addr_reg_622 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);
                linebuf_y_val_V_1_addr_reg_617 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);
                linebuf_y_val_V_addr_reg_611 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (sel_tmp4_read_reg_592 = ap_const_lv1_1) and (sel_tmp6_read_reg_587 = ap_const_lv1_0))) then
                ret_V_21_reg_666 <= ret_V_21_fu_420_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0))) then
                rhs_reg_649 <= rhs_fu_401_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (sel_tmp6_read_reg_587 = ap_const_lv1_0))) then
                    zext_ln1495_2_reg_661(7 downto 0) <= zext_ln1495_2_fu_416_p1(7 downto 0);
            end if;
        end if;
    end process;
    zext_ln1495_2_reg_661(8) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    SrcYUV422_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, SrcYUV422_full_n, ap_predicate_op82_write_state3, ap_predicate_op103_write_state4, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            SrcYUV422_blk_n <= SrcYUV422_full_n;
        else 
            SrcYUV422_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    SrcYUV422_din_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_predicate_op82_write_state3, ap_predicate_op103_write_state4, p_0_fu_438_p4, ap_block_pp0_stage0_01001, zext_ln1184_fu_547_p1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_01001)) then
            if (((ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                SrcYUV422_din <= zext_ln1184_fu_547_p1;
            elsif (((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                SrcYUV422_din <= p_0_fu_438_p4;
            else 
                SrcYUV422_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            SrcYUV422_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    SrcYUV422_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_predicate_op82_write_state3, ap_predicate_op103_write_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            SrcYUV422_write <= ap_const_logic_1;
        else 
            SrcYUV422_write <= ap_const_logic_0;
        end if; 
    end process;


    SrcYUV_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, SrcYUV_empty_n, ap_predicate_op36_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op36_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            SrcYUV_blk_n <= SrcYUV_empty_n;
        else 
            SrcYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    SrcYUV_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op36_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op36_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            SrcYUV_read <= ap_const_logic_1;
        else 
            SrcYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    add_ln1012_fu_309_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_out_x) + unsigned(ap_const_lv11_1));
    add_ln1495_1_fu_476_p2 <= std_logic_vector(unsigned(add_ln1495_2_fu_470_p2) + unsigned(zext_ln1495_1_fu_463_p1));
    add_ln1495_2_fu_470_p2 <= std_logic_vector(unsigned(zext_ln1495_3_fu_467_p1) + unsigned(zext_ln1495_fu_459_p1));
    add_ln1495_3_fu_492_p2 <= std_logic_vector(unsigned(zext_ln1494_fu_449_p1) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, SrcYUV_empty_n, ap_predicate_op36_read_state2, SrcYUV422_full_n, ap_predicate_op82_write_state3, ap_predicate_op103_write_state4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op36_read_state2 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV_empty_n) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, SrcYUV_empty_n, ap_predicate_op36_read_state2, SrcYUV422_full_n, ap_predicate_op82_write_state3, ap_predicate_op103_write_state4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op36_read_state2 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV_empty_n) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, SrcYUV_empty_n, ap_predicate_op36_read_state2, SrcYUV422_full_n, ap_predicate_op82_write_state3, ap_predicate_op103_write_state4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op36_read_state2 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV_empty_n) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(SrcYUV_empty_n, ap_predicate_op36_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op36_read_state2 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV_empty_n));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(SrcYUV422_full_n, ap_predicate_op82_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op82_write_state3 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(SrcYUV422_full_n, ap_predicate_op103_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((ap_predicate_op103_write_state4 = ap_const_boolean_1) and (ap_const_logic_0 = SrcYUV422_full_n));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1012_fu_303_p2)
    begin
        if (((icmp_ln1012_fu_303_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln1012_reg_607 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_47_assign_proc : process(icmp_ln1012_reg_607)
    begin
                ap_enable_operation_47 <= (icmp_ln1012_reg_607 = ap_const_lv1_0);
    end process;


    ap_enable_operation_50_assign_proc : process(icmp_ln1012_reg_607)
    begin
                ap_enable_operation_50 <= (icmp_ln1012_reg_607 = ap_const_lv1_0);
    end process;


    ap_enable_operation_52_assign_proc : process(icmp_ln1012_reg_607)
    begin
                ap_enable_operation_52 <= (icmp_ln1012_reg_607 = ap_const_lv1_0);
    end process;


    ap_enable_operation_58_assign_proc : process(icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_enable_operation_58 <= (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_59_assign_proc : process(ap_predicate_op59_load_state3)
    begin
                ap_enable_operation_59 <= (ap_predicate_op59_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_60_assign_proc : process(icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_enable_operation_60 <= (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_62_assign_proc : process(icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_enable_operation_62 <= (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_63_assign_proc : process(icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_enable_operation_63 <= (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_64_assign_proc : process(icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_enable_operation_64 <= (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_67_assign_proc : process(ap_predicate_op67_store_state3)
    begin
                ap_enable_operation_67 <= (ap_predicate_op67_store_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_71_assign_proc : process(ap_predicate_op71_store_state3)
    begin
                ap_enable_operation_71 <= (ap_predicate_op71_store_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_84_assign_proc : process(ap_predicate_op84_load_state4)
    begin
                ap_enable_operation_84 <= (ap_predicate_op84_load_state4 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state4_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4_assign_proc : process(cmp36_read_reg_568, cmp36, linebuf_c_val_V_q1, spec_select, p_0_1_0_0_0878_out_i, icmp_ln1012_reg_607_pp0_iter1_reg, ap_phi_reg_pp0_iter2_p_0_0_0_0_0404883_reg_265)
    begin
        if (((icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select = ap_const_lv1_0))) then
            if ((cmp36_read_reg_568 = ap_const_lv1_0)) then 
                ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4 <= linebuf_c_val_V_q1;
            elsif ((cmp36 = ap_const_lv1_1)) then 
                ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4 <= p_0_1_0_0_0878_out_i;
            else 
                ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4 <= ap_phi_reg_pp0_iter2_p_0_0_0_0_0404883_reg_265;
            end if;
        else 
            ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4 <= ap_phi_reg_pp0_iter2_p_0_0_0_0_0404883_reg_265;
        end if; 
    end process;


    ap_phi_mux_rhs_2_phi_fu_278_p4_assign_proc : process(linebuf_c_val_V_q1, spec_select, spec_select_read_reg_563, icmp_ln1012_reg_607_pp0_iter1_reg, ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4, ap_phi_reg_pp0_iter2_rhs_2_reg_275)
    begin
        if ((icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((spec_select_read_reg_563 = ap_const_lv1_1)) then 
                ap_phi_mux_rhs_2_phi_fu_278_p4 <= linebuf_c_val_V_q1;
            elsif ((spec_select = ap_const_lv1_0)) then 
                ap_phi_mux_rhs_2_phi_fu_278_p4 <= ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4;
            else 
                ap_phi_mux_rhs_2_phi_fu_278_p4 <= ap_phi_reg_pp0_iter2_rhs_2_reg_275;
            end if;
        else 
            ap_phi_mux_rhs_2_phi_fu_278_p4 <= ap_phi_reg_pp0_iter2_rhs_2_reg_275;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_lhs_reg_286 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter2_p_0_0_0_0_0404883_reg_265 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter2_rhs_2_reg_275 <= "XXXXXXXX";

    ap_predicate_op103_write_state4_assign_proc : process(cmp391, icmp_ln995)
    begin
                ap_predicate_op103_write_state4 <= ((icmp_ln995 = ap_const_lv1_0) and (cmp391 = ap_const_lv1_1));
    end process;


    ap_predicate_op36_read_state2_assign_proc : process(icmp_ln1012_reg_607, cmp36)
    begin
                ap_predicate_op36_read_state2 <= ((cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0));
    end process;


    ap_predicate_op59_load_state3_assign_proc : process(cmp287, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_predicate_op59_load_state3 <= ((icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (cmp287 = ap_const_lv1_0));
    end process;


    ap_predicate_op67_store_state3_assign_proc : process(cmp36, spec_select, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_predicate_op67_store_state3 <= ((cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select = ap_const_lv1_0));
    end process;


    ap_predicate_op71_store_state3_assign_proc : process(spec_select, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
                ap_predicate_op71_store_state3 <= ((icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select = ap_const_lv1_0));
    end process;


    ap_predicate_op82_write_state3_assign_proc : process(cmp391, icmp_ln995)
    begin
                ap_predicate_op82_write_state3 <= ((icmp_ln995 = ap_const_lv1_1) and (cmp391 = ap_const_lv1_1));
    end process;


    ap_predicate_op84_load_state4_assign_proc : process(cmp287, icmp_ln1012_reg_607_pp0_iter2_reg)
    begin
                ap_predicate_op84_load_state4 <= ((icmp_ln1012_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (cmp287 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_out_x_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_112, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_out_x <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_out_x <= x_fu_112;
        end if; 
    end process;

    cmp36_read_reg_568 <= cmp36;
    icmp_ln1012_fu_303_p2 <= "1" when (ap_sig_allocacmp_out_x = loopWidth) else "0";
    linebuf_c_val_V_1_address0 <= linebuf_c_val_V_1_addr_reg_628;
    linebuf_c_val_V_1_address1 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);

    linebuf_c_val_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf_c_val_V_1_ce0 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_c_val_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_c_val_V_1_ce1 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_c_val_V_1_d0 <= 
        rhs_fu_401_p3 when (cmp104(0) = '1') else 
        ap_phi_mux_p_0_0_0_0_0404883_phi_fu_268_p4;

    linebuf_c_val_V_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, spec_select, ap_block_pp0_stage0_11001, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select = ap_const_lv1_0))) then 
            linebuf_c_val_V_1_we0 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_c_val_V_2_address0 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);

    linebuf_c_val_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_c_val_V_2_ce0 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_c_val_V_address0 <= linebuf_c_val_V_addr_reg_622;
    linebuf_c_val_V_address1 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);

    linebuf_c_val_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf_c_val_V_ce0 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_c_val_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_c_val_V_ce1 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_c_val_V_d0 <= p_0_1_0_0_0878_out_i;

    linebuf_c_val_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, cmp36, spec_select, ap_block_pp0_stage0_11001, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp36 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0) and (spec_select = ap_const_lv1_0))) then 
            linebuf_c_val_V_we0 <= ap_const_logic_1;
        else 
            linebuf_c_val_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_y_val_V_1_address0 <= linebuf_y_val_V_1_addr_reg_617;

    linebuf_y_val_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0))) then 
            linebuf_y_val_V_1_ce0 <= ap_const_logic_1;
        else 
            linebuf_y_val_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_y_val_V_1_d0 <= 
        linebuf_y_val_V_q1 when (cmp104(0) = '1') else 
        p_0_0_0_0_0423876_out_i;

    linebuf_y_val_V_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0))) then 
            linebuf_y_val_V_1_we0 <= ap_const_logic_1;
        else 
            linebuf_y_val_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_y_val_V_address0 <= linebuf_y_val_V_addr_reg_611;
    linebuf_y_val_V_address1 <= zext_ln1012_fu_320_p1(11 - 1 downto 0);

    linebuf_y_val_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linebuf_y_val_V_ce0 <= ap_const_logic_1;
        else 
            linebuf_y_val_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linebuf_y_val_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            linebuf_y_val_V_ce1 <= ap_const_logic_1;
        else 
            linebuf_y_val_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    linebuf_y_val_V_d0 <= p_0_0_0_0_0423876_out_i;

    linebuf_y_val_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln1012_reg_607_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1012_reg_607_pp0_iter1_reg = ap_const_lv1_0))) then 
            linebuf_y_val_V_we0 <= ap_const_logic_1;
        else 
            linebuf_y_val_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_0_0_0_0_0406889894_fu_526_p3 <= 
        ap_const_lv8_0 when (sel_tmp6(0) = '1') else 
        sel_tmp5_fu_519_p3;

    p_0_0_0_0_0423870_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, p_0_0_0_0_0423870_out_i, ap_block_pp0_stage0, trunc_ln1022_fu_328_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_0_0_0423870_out_o <= trunc_ln1022_fu_328_p1;
        else 
            p_0_0_0_0_0423870_out_o <= p_0_0_0_0_0423870_out_i;
        end if; 
    end process;


    p_0_0_0_0_0423870_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_0_0_0423870_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0_0423870_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_0_0_0_0423876_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, p_0_0_0_0_0423876_out_i, ap_block_pp0_stage0, trunc_ln1022_fu_328_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_0_0_0423876_out_o <= trunc_ln1022_fu_328_p1;
        else 
            p_0_0_0_0_0423876_out_o <= p_0_0_0_0_0423876_out_i;
        end if; 
    end process;


    p_0_0_0_0_0423876_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_0_0_0423876_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0_0423876_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_1_0_0_0872_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, SrcYUV_dout, icmp_ln1012_reg_607, cmp36, p_0_1_0_0_0872_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_0872_out_o <= SrcYUV_dout(15 downto 8);
        else 
            p_0_1_0_0_0872_out_o <= p_0_1_0_0_0872_out_i;
        end if; 
    end process;


    p_0_1_0_0_0872_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_0872_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_1_0_0_0872_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_1_0_0_0878_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, SrcYUV_dout, icmp_ln1012_reg_607, cmp36, p_0_1_0_0_0878_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_0878_out_o <= SrcYUV_dout(15 downto 8);
        else 
            p_0_1_0_0_0878_out_o <= p_0_1_0_0_0878_out_i;
        end if; 
    end process;


    p_0_1_0_0_0878_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_0878_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_1_0_0_0878_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_2_0_0_0874_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, SrcYUV_dout, icmp_ln1012_reg_607, cmp36, p_0_2_0_0_0874_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_2_0_0_0874_out_o <= SrcYUV_dout(23 downto 16);
        else 
            p_0_2_0_0_0874_out_o <= p_0_2_0_0_0874_out_i;
        end if; 
    end process;


    p_0_2_0_0_0874_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1012_reg_607, cmp36, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp36 = ap_const_lv1_1) and (icmp_ln1012_reg_607 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_2_0_0_0874_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_2_0_0_0874_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_fu_438_p4 <= ((p_0_2_0_0_0874_out_i & p_0_1_0_0_0872_out_i) & p_0_0_0_0_0423870_out_i);
    ret_4_fu_533_p3 <= 
        LineBufVal_V_14_reg_639 when (cmp287(0) = '1') else 
        linebuf_y_val_V_1_q0;
    ret_V_20_fu_452_p3 <= (rhs_reg_649 & ap_const_lv1_0);
    ret_V_21_fu_420_p2 <= std_logic_vector(unsigned(zext_ln1495_2_fu_416_p1) + unsigned(ap_const_lv9_2));
    ret_V_fu_498_p2 <= std_logic_vector(unsigned(add_ln1495_3_fu_492_p2) + unsigned(zext_ln1495_2_reg_661));
    rhs_fu_401_p3 <= 
        linebuf_c_val_V_1_q1 when (spec_select(0) = '1') else 
        linebuf_c_val_V_q1;
    sel_tmp2_fu_513_p3 <= 
        trunc_ln186_1_fu_503_p4 when (sel_tmp1(0) = '1') else 
        rhs_reg_649;
    sel_tmp4_read_reg_592 <= sel_tmp4;
    sel_tmp5_fu_519_p3 <= 
        trunc_ln3_fu_482_p4 when (sel_tmp4(0) = '1') else 
        sel_tmp2_fu_513_p3;
    sel_tmp6_read_reg_587 <= sel_tmp6;
    spec_select_read_reg_563 <= spec_select;
    tmp_1_fu_539_p3 <= (p_0_0_0_0_0406889894_fu_526_p3 & ret_4_fu_533_p3);
    trunc_ln1022_fu_328_p1 <= SrcYUV_dout(8 - 1 downto 0);
    trunc_ln186_1_fu_503_p4 <= ret_V_fu_498_p2(8 downto 1);
    trunc_ln3_fu_482_p4 <= add_ln1495_1_fu_476_p2(9 downto 2);
    zext_ln1012_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_x_reg_602),64));
    zext_ln1184_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_539_p3),24));
    zext_ln1494_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_reg_649),9));
    zext_ln1495_1_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_20_fu_452_p3),10));
    zext_ln1495_2_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_rhs_2_phi_fu_278_p4),9));
    zext_ln1495_3_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_21_reg_666),10));
    zext_ln1495_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_lhs_reg_286),10));
end behav;
