// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_eab1_hsc_0_Block_entry1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        ColorMode,
        ColorModeOut,
        ColorMode_c_din,
        ColorMode_c_num_data_valid,
        ColorMode_c_fifo_cap,
        ColorMode_c_full_n,
        ColorMode_c_write,
        ColorModeOut_c_din,
        ColorModeOut_c_num_data_valid,
        ColorModeOut_c_fifo_cap,
        ColorModeOut_c_full_n,
        ColorModeOut_c_write,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] ColorMode;
input  [7:0] ColorModeOut;
output  [7:0] ColorMode_c_din;
input  [2:0] ColorMode_c_num_data_valid;
input  [2:0] ColorMode_c_fifo_cap;
input   ColorMode_c_full_n;
output   ColorMode_c_write;
output  [7:0] ColorModeOut_c_din;
input  [3:0] ColorModeOut_c_num_data_valid;
input  [3:0] ColorModeOut_c_fifo_cap;
input   ColorModeOut_c_full_n;
output   ColorModeOut_c_write;
output  [0:0] ap_return_0;
output  [0:0] ap_return_1;
output  [0:0] ap_return_2;
output  [0:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg start_write;
reg ColorMode_c_write;
reg ColorModeOut_c_write;
reg[0:0] ap_return_0;
reg[0:0] ap_return_1;
reg[0:0] ap_return_2;
reg[0:0] ap_return_3;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    ColorMode_c_blk_n;
reg    ColorModeOut_c_blk_n;
reg    ap_block_state1;
wire   [0:0] icmp_ln110_fu_80_p2;
wire   [0:0] icmp_ln110_1_fu_86_p2;
wire   [0:0] icmp_ln110_2_fu_98_p2;
wire   [0:0] icmp_ln110_3_fu_104_p2;
wire   [0:0] and_ln110_fu_92_p2;
wire   [0:0] and_ln110_1_fu_110_p2;
wire   [0:0] or_ln110_fu_116_p2;
wire   [0:0] icmp_ln115_fu_128_p2;
wire   [0:0] icmp_ln115_1_fu_134_p2;
wire   [0:0] or_ln115_fu_140_p2;
wire   [0:0] bPassThruHcr1_fu_74_p2;
wire   [0:0] bPassThruCsc_fu_122_p2;
wire   [0:0] bPassThruHcr2_fu_146_p2;
wire   [0:0] bPassThruVcr_fu_152_p2;
reg   [0:0] ap_return_0_preg;
reg   [0:0] ap_return_1_preg;
reg   [0:0] ap_return_2_preg;
reg   [0:0] ap_return_3_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 1'd0;
#0 ap_return_1_preg = 1'd0;
#0 ap_return_2_preg = 1'd0;
#0 ap_return_3_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 1'd0;
    end else begin
        if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= bPassThruHcr1_fu_74_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 1'd0;
    end else begin
        if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= bPassThruCsc_fu_122_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 1'd0;
    end else begin
        if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= bPassThruHcr2_fu_146_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 1'd0;
    end else begin
        if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= bPassThruVcr_fu_152_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorModeOut_c_blk_n = ColorModeOut_c_full_n;
    end else begin
        ColorModeOut_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorModeOut_c_write = 1'b1;
    end else begin
        ColorModeOut_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_c_blk_n = ColorMode_c_full_n;
    end else begin
        ColorMode_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_c_write = 1'b1;
    end else begin
        ColorMode_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = bPassThruHcr1_fu_74_p2;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = bPassThruCsc_fu_122_p2;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = bPassThruHcr2_fu_146_p2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = bPassThruVcr_fu_152_p2;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ColorModeOut_c_din = ColorModeOut;

assign ColorMode_c_din = ColorMode;

assign and_ln110_1_fu_110_p2 = (icmp_ln110_3_fu_104_p2 & icmp_ln110_2_fu_98_p2);

assign and_ln110_fu_92_p2 = (icmp_ln110_fu_80_p2 & icmp_ln110_1_fu_86_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (1'b0 == ColorModeOut_c_full_n) | (1'b0 == ColorMode_c_full_n) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign bPassThruCsc_fu_122_p2 = (or_ln110_fu_116_p2 ^ 1'd1);

assign bPassThruHcr1_fu_74_p2 = ((ColorMode != 8'd2) ? 1'b1 : 1'b0);

assign bPassThruHcr2_fu_146_p2 = (or_ln115_fu_140_p2 ^ 1'd1);

assign bPassThruVcr_fu_152_p2 = (icmp_ln115_1_fu_134_p2 ^ 1'd1);

assign icmp_ln110_1_fu_86_p2 = ((ColorModeOut != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_2_fu_98_p2 = ((ColorMode != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_3_fu_104_p2 = ((ColorModeOut == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_80_p2 = ((ColorMode == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln115_1_fu_134_p2 = ((ColorModeOut == 8'd3) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_128_p2 = ((ColorModeOut == 8'd2) ? 1'b1 : 1'b0);

assign or_ln110_fu_116_p2 = (and_ln110_fu_92_p2 | and_ln110_1_fu_110_p2);

assign or_ln115_fu_140_p2 = (icmp_ln115_fu_128_p2 | icmp_ln115_1_fu_134_p2);

assign start_out = real_start;

endmodule //bd_eab1_hsc_0_Block_entry1_proc
