-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ISPPipeline_accel_AWBNormalizationkernel_Pipeline_Col_Loop1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    impop_data1_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    impop_data1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    impop_data1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    impop_data1_empty_n : IN STD_LOGIC;
    impop_data1_read : OUT STD_LOGIC;
    ltm_in_data217_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    ltm_in_data217_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ltm_in_data217_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ltm_in_data217_full_n : IN STD_LOGIC;
    ltm_in_data217_write : OUT STD_LOGIC;
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    empty_102 : IN STD_LOGIC_VECTOR (17 downto 0);
    conv7_i178 : IN STD_LOGIC_VECTOR (25 downto 0);
    empty_103 : IN STD_LOGIC_VECTOR (17 downto 0);
    conv7_i178_1 : IN STD_LOGIC_VECTOR (25 downto 0);
    empty : IN STD_LOGIC_VECTOR (17 downto 0);
    conv7_i178_2 : IN STD_LOGIC_VECTOR (25 downto 0) );
end;


architecture behav of ISPPipeline_accel_AWBNormalizationkernel_Pipeline_Col_Loop1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1027_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal impop_data1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ltm_in_data217_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv7_i178_2_cast_fu_157_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal conv7_i178_2_cast_reg_603 : STD_LOGIC_VECTOR (43 downto 0);
    signal conv7_i178_1_cast_fu_161_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal conv7_i178_1_cast_reg_608 : STD_LOGIC_VECTOR (43 downto 0);
    signal conv7_i178_cast_fu_165_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal conv7_i178_cast_reg_613 : STD_LOGIC_VECTOR (43 downto 0);
    signal trunc_ln813_fu_198_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln813_reg_622 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_13_reg_627 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_15_reg_632 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_61_reg_652 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln214_fu_357_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln214_reg_657 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_63_reg_662 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln214_5_fu_436_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln214_5_reg_667 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_65_reg_672 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln214_6_fu_515_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln214_6_reg_677 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln214_fu_524_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln214_reg_682 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln214_3_fu_536_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln214_3_reg_687 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln214_4_fu_548_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln214_4_reg_692 : STD_LOGIC_VECTOR (9 downto 0);
    signal col_V_fu_98 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_4_fu_187_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_V_3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1027_fu_177_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_222_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln813_fu_229_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal value_V_fu_233_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln813_1_fu_242_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln813_1_fu_249_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal value_V_1_fu_253_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln813_2_fu_262_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln813_2_fu_269_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal value_V_2_fu_273_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_563_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_s_fu_282_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln6_fu_291_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln1273_1_fu_303_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln1273_fu_299_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal sext_ln1273_1_fu_311_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal r_V_14_fu_315_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_60_fu_331_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal finalmul_V_fu_321_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal dstval_V_fu_339_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_569_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_14_fu_361_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1273_2_fu_370_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln1273_3_fu_382_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln1273_2_fu_378_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal sext_ln1273_3_fu_390_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal r_V_17_fu_394_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_62_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal finalmul_V_1_fu_400_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal dstval_V_2_fu_418_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_575_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_16_fu_440_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1273_4_fu_449_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln1273_5_fu_461_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln1273_4_fu_457_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal sext_ln1273_5_fu_469_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal r_V_20_fu_473_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_64_fu_489_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal finalmul_V_2_fu_479_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal dstval_V_3_fu_497_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln44_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_1_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_2_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_563_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_569_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_575_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_563_ce : STD_LOGIC;
    signal grp_fu_569_ce : STD_LOGIC;
    signal grp_fu_575_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ISPPipeline_accel_mul_mul_26s_18s_44_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component ISPPipeline_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_mul_26s_18s_44_4_1_U291 : component ISPPipeline_accel_mul_mul_26s_18s_44_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 26,
        din1_WIDTH => 18,
        dout_WIDTH => 44)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_563_p0,
        din1 => value_V_fu_233_p2,
        ce => grp_fu_563_ce,
        dout => grp_fu_563_p2);

    mul_mul_26s_18s_44_4_1_U292 : component ISPPipeline_accel_mul_mul_26s_18s_44_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 26,
        din1_WIDTH => 18,
        dout_WIDTH => 44)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_569_p0,
        din1 => value_V_1_fu_253_p2,
        ce => grp_fu_569_ce,
        dout => grp_fu_569_p2);

    mul_mul_26s_18s_44_4_1_U293 : component ISPPipeline_accel_mul_mul_26s_18s_44_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 26,
        din1_WIDTH => 18,
        dout_WIDTH => 44)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_575_p0,
        din1 => value_V_2_fu_273_p2,
        ce => grp_fu_575_ce,
        dout => grp_fu_575_p2);

    flow_control_loop_pipe_sequential_init_U : component ISPPipeline_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    col_V_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1027_fu_181_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    col_V_fu_98 <= col_V_4_fu_187_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_V_fu_98 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                conv7_i178_1_cast_reg_608 <= conv7_i178_1_cast_fu_161_p1;
                conv7_i178_2_cast_reg_603 <= conv7_i178_2_cast_fu_157_p1;
                conv7_i178_cast_reg_613 <= conv7_i178_cast_fu_165_p1;
                tmp_13_reg_627 <= impop_data1_dout(19 downto 10);
                tmp_15_reg_632 <= impop_data1_dout(29 downto 20);
                trunc_ln813_reg_622 <= trunc_ln813_fu_198_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                select_ln214_3_reg_687 <= select_ln214_3_fu_536_p3;
                select_ln214_4_reg_692 <= select_ln214_4_fu_548_p3;
                select_ln214_reg_682 <= select_ln214_fu_524_p3;
                tmp_61_reg_652 <= dstval_V_fu_339_p3(24 downto 10);
                tmp_63_reg_662 <= dstval_V_2_fu_418_p3(24 downto 10);
                tmp_65_reg_672 <= dstval_V_3_fu_497_p3(24 downto 10);
                trunc_ln214_5_reg_667 <= trunc_ln214_5_fu_436_p1;
                trunc_ln214_6_reg_677 <= trunc_ln214_6_fu_515_p1;
                trunc_ln214_reg_657 <= trunc_ln214_fu_357_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, impop_data1_empty_n, ltm_in_data217_full_n)
    begin
                ap_block_pp0_stage0_01001 <= (((ltm_in_data217_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((impop_data1_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, impop_data1_empty_n, ltm_in_data217_full_n)
    begin
                ap_block_pp0_stage0_11001 <= (((ltm_in_data217_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((impop_data1_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, impop_data1_empty_n, ltm_in_data217_full_n)
    begin
                ap_block_pp0_stage0_subdone <= (((ltm_in_data217_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((impop_data1_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(impop_data1_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (impop_data1_empty_n = ap_const_logic_0);
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter7_assign_proc : process(ltm_in_data217_full_n)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (ltm_in_data217_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1027_fu_181_p2)
    begin
        if (((icmp_ln1027_fu_181_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_V_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_V_fu_98, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_col_V_3 <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_col_V_3 <= col_V_fu_98;
        end if; 
    end process;

    col_V_4_fu_187_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_col_V_3) + unsigned(ap_const_lv13_1));
        conv7_i178_1_cast_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i178_1),44));

        conv7_i178_2_cast_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i178_2),44));

        conv7_i178_cast_fu_165_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i178),44));

    dstval_V_2_fu_418_p3 <= 
        ap_const_lv25_0 when (tmp_62_fu_410_p3(0) = '1') else 
        finalmul_V_1_fu_400_p4;
    dstval_V_3_fu_497_p3 <= 
        ap_const_lv25_0 when (tmp_64_fu_489_p3(0) = '1') else 
        finalmul_V_2_fu_479_p4;
    dstval_V_fu_339_p3 <= 
        ap_const_lv25_0 when (tmp_60_fu_331_p3(0) = '1') else 
        finalmul_V_fu_321_p4;
    finalmul_V_1_fu_400_p4 <= r_V_17_fu_394_p2(48 downto 24);
    finalmul_V_2_fu_479_p4 <= r_V_20_fu_473_p2(48 downto 24);
    finalmul_V_fu_321_p4 <= r_V_14_fu_315_p2(48 downto 24);

    grp_fu_563_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_563_ce <= ap_const_logic_1;
        else 
            grp_fu_563_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_563_p0 <= conv7_i178_cast_reg_613(26 - 1 downto 0);

    grp_fu_569_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_569_ce <= ap_const_logic_1;
        else 
            grp_fu_569_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_569_p0 <= conv7_i178_1_cast_reg_608(26 - 1 downto 0);

    grp_fu_575_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_575_ce <= ap_const_logic_1;
        else 
            grp_fu_575_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_575_p0 <= conv7_i178_2_cast_reg_603(26 - 1 downto 0);
    icmp_ln1027_fu_181_p2 <= "1" when (signed(zext_ln1027_fu_177_p1) < signed(p_read1)) else "0";
    icmp_ln44_1_fu_531_p2 <= "1" when (signed(tmp_63_reg_662) > signed(ap_const_lv15_0)) else "0";
    icmp_ln44_2_fu_543_p2 <= "1" when (signed(tmp_65_reg_672) > signed(ap_const_lv15_0)) else "0";
    icmp_ln44_fu_519_p2 <= "1" when (signed(tmp_61_reg_652) > signed(ap_const_lv15_0)) else "0";

    impop_data1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, impop_data1_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            impop_data1_blk_n <= impop_data1_empty_n;
        else 
            impop_data1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    impop_data1_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            impop_data1_read <= ap_const_logic_1;
        else 
            impop_data1_read <= ap_const_logic_0;
        end if; 
    end process;


    ltm_in_data217_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, ltm_in_data217_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            ltm_in_data217_blk_n <= ltm_in_data217_full_n;
        else 
            ltm_in_data217_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ltm_in_data217_din <= ((select_ln214_4_reg_692 & select_ln214_3_reg_687) & select_ln214_reg_682);

    ltm_in_data217_write_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            ltm_in_data217_write <= ap_const_logic_1;
        else 
            ltm_in_data217_write <= ap_const_logic_0;
        end if; 
    end process;

    r_V_14_fu_315_p2 <= std_logic_vector(signed(sext_ln1273_fu_299_p1) - signed(sext_ln1273_1_fu_311_p1));
    r_V_17_fu_394_p2 <= std_logic_vector(signed(sext_ln1273_2_fu_378_p1) - signed(sext_ln1273_3_fu_390_p1));
    r_V_20_fu_473_p2 <= std_logic_vector(signed(sext_ln1273_4_fu_457_p1) - signed(sext_ln1273_5_fu_469_p1));
    select_ln214_3_fu_536_p3 <= 
        ap_const_lv10_3FF when (icmp_ln44_1_fu_531_p2(0) = '1') else 
        trunc_ln214_5_reg_667;
    select_ln214_4_fu_548_p3 <= 
        ap_const_lv10_3FF when (icmp_ln44_2_fu_543_p2(0) = '1') else 
        trunc_ln214_6_reg_677;
    select_ln214_fu_524_p3 <= 
        ap_const_lv10_3FF when (icmp_ln44_fu_519_p2(0) = '1') else 
        trunc_ln214_reg_657;
        sext_ln1273_1_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_303_p3),49));

        sext_ln1273_2_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_2_fu_370_p3),49));

        sext_ln1273_3_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_382_p3),49));

        sext_ln1273_4_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_4_fu_449_p3),49));

        sext_ln1273_5_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_461_p3),49));

        sext_ln1273_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln6_fu_291_p3),49));

    shl_ln1273_1_fu_303_p3 <= (tmp_s_fu_282_p4 & ap_const_lv6_0);
    shl_ln1273_2_fu_370_p3 <= (tmp_14_fu_361_p4 & ap_const_lv16_0);
    shl_ln1273_3_fu_382_p3 <= (tmp_14_fu_361_p4 & ap_const_lv6_0);
    shl_ln1273_4_fu_449_p3 <= (tmp_16_fu_440_p4 & ap_const_lv16_0);
    shl_ln1273_5_fu_461_p3 <= (tmp_16_fu_440_p4 & ap_const_lv6_0);
    shl_ln6_fu_291_p3 <= (tmp_s_fu_282_p4 & ap_const_lv16_0);
    shl_ln813_1_fu_242_p3 <= (tmp_13_reg_627 & ap_const_lv6_0);
    shl_ln813_2_fu_262_p3 <= (tmp_15_reg_632 & ap_const_lv6_0);
    shl_ln_fu_222_p3 <= (trunc_ln813_reg_622 & ap_const_lv6_0);
    tmp_14_fu_361_p4 <= grp_fu_569_p2(43 downto 12);
    tmp_16_fu_440_p4 <= grp_fu_575_p2(43 downto 12);
    tmp_60_fu_331_p3 <= r_V_14_fu_315_p2(48 downto 48);
    tmp_62_fu_410_p3 <= r_V_17_fu_394_p2(48 downto 48);
    tmp_64_fu_489_p3 <= r_V_20_fu_473_p2(48 downto 48);
    tmp_s_fu_282_p4 <= grp_fu_563_p2(43 downto 12);
    trunc_ln214_5_fu_436_p1 <= dstval_V_2_fu_418_p3(10 - 1 downto 0);
    trunc_ln214_6_fu_515_p1 <= dstval_V_3_fu_497_p3(10 - 1 downto 0);
    trunc_ln214_fu_357_p1 <= dstval_V_fu_339_p3(10 - 1 downto 0);
    trunc_ln813_fu_198_p1 <= impop_data1_dout(10 - 1 downto 0);
    value_V_1_fu_253_p2 <= std_logic_vector(unsigned(zext_ln813_1_fu_249_p1) - unsigned(empty_103));
    value_V_2_fu_273_p2 <= std_logic_vector(unsigned(zext_ln813_2_fu_269_p1) - unsigned(empty));
    value_V_fu_233_p2 <= std_logic_vector(unsigned(zext_ln813_fu_229_p1) - unsigned(empty_102));
    zext_ln1027_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_V_3),16));
    zext_ln813_1_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln813_1_fu_242_p3),18));
    zext_ln813_2_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln813_2_fu_262_p3),18));
    zext_ln813_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_222_p3),18));
end behav;
