// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_eab1_hsc_0_v_csc_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_scaled_dout,
        stream_scaled_num_data_valid,
        stream_scaled_fifo_cap,
        stream_scaled_empty_n,
        stream_scaled_read,
        Height_dout,
        Height_num_data_valid,
        Height_fifo_cap,
        Height_empty_n,
        Height_read,
        WidthOut_dout,
        WidthOut_num_data_valid,
        WidthOut_fifo_cap,
        WidthOut_empty_n,
        WidthOut_read,
        ColorMode_dout,
        ColorMode_num_data_valid,
        ColorMode_fifo_cap,
        ColorMode_empty_n,
        ColorMode_read,
        p_read,
        stream_scaled_csc_din,
        stream_scaled_csc_num_data_valid,
        stream_scaled_csc_fifo_cap,
        stream_scaled_csc_full_n,
        stream_scaled_csc_write,
        Height_c18_din,
        Height_c18_num_data_valid,
        Height_c18_fifo_cap,
        Height_c18_full_n,
        Height_c18_write,
        WidthOut_c22_din,
        WidthOut_c22_num_data_valid,
        WidthOut_c22_fifo_cap,
        WidthOut_c22_full_n,
        WidthOut_c22_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_scaled_dout;
input  [4:0] stream_scaled_num_data_valid;
input  [4:0] stream_scaled_fifo_cap;
input   stream_scaled_empty_n;
output   stream_scaled_read;
input  [15:0] Height_dout;
input  [1:0] Height_num_data_valid;
input  [1:0] Height_fifo_cap;
input   Height_empty_n;
output   Height_read;
input  [15:0] WidthOut_dout;
input  [1:0] WidthOut_num_data_valid;
input  [1:0] WidthOut_fifo_cap;
input   WidthOut_empty_n;
output   WidthOut_read;
input  [7:0] ColorMode_dout;
input  [2:0] ColorMode_num_data_valid;
input  [2:0] ColorMode_fifo_cap;
input   ColorMode_empty_n;
output   ColorMode_read;
input  [0:0] p_read;
output  [23:0] stream_scaled_csc_din;
input  [4:0] stream_scaled_csc_num_data_valid;
input  [4:0] stream_scaled_csc_fifo_cap;
input   stream_scaled_csc_full_n;
output   stream_scaled_csc_write;
output  [15:0] Height_c18_din;
input  [1:0] Height_c18_num_data_valid;
input  [1:0] Height_c18_fifo_cap;
input   Height_c18_full_n;
output   Height_c18_write;
output  [15:0] WidthOut_c22_din;
input  [1:0] WidthOut_c22_num_data_valid;
input  [1:0] WidthOut_c22_fifo_cap;
input   WidthOut_c22_full_n;
output   WidthOut_c22_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_scaled_read;
reg Height_read;
reg WidthOut_read;
reg ColorMode_read;
reg stream_scaled_csc_write;
reg Height_c18_write;
reg WidthOut_c22_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    WidthOut_blk_n;
reg    ColorMode_blk_n;
reg    Height_c18_blk_n;
reg    WidthOut_c22_blk_n;
wire   [10:0] empty_fu_125_p1;
reg   [10:0] empty_reg_175;
wire   [10:0] empty_76_fu_129_p1;
reg   [10:0] empty_76_reg_180;
wire   [0:0] cmp73_fu_133_p2;
reg   [0:0] cmp73_reg_185;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_done;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_idle;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_ready;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_read;
wire   [23:0] grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_csc_din;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_csc_write;
reg    grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln2033_fu_147_p2;
wire    ap_CS_fsm_state3;
reg   [10:0] y_fu_70;
wire   [10:0] y_7_fu_152_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start_reg = 1'b0;
end

bd_eab1_hsc_0_v_csc_core_Pipeline_VITIS_LOOP_2035_2 grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start),
    .ap_done(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_done),
    .ap_idle(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_idle),
    .ap_ready(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_ready),
    .stream_scaled_dout(stream_scaled_dout),
    .stream_scaled_num_data_valid(5'd0),
    .stream_scaled_fifo_cap(5'd0),
    .stream_scaled_empty_n(stream_scaled_empty_n),
    .stream_scaled_read(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_read),
    .stream_scaled_csc_din(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_csc_din),
    .stream_scaled_csc_num_data_valid(5'd0),
    .stream_scaled_csc_fifo_cap(5'd0),
    .stream_scaled_csc_full_n(stream_scaled_csc_full_n),
    .stream_scaled_csc_write(grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_csc_write),
    .WidthOut_load_cast(empty_reg_175),
    .cmp73(cmp73_reg_185),
    .p_read(p_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2033_fu_147_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2033_fu_147_p2 == 1'd0))) begin
            grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start_reg <= 1'b1;
        end else if ((grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_ready == 1'b1)) begin
            grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_70 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2033_fu_147_p2 == 1'd0))) begin
        y_fu_70 <= y_7_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp73_reg_185 <= cmp73_fu_133_p2;
        empty_76_reg_180 <= empty_76_fu_129_p1;
        empty_reg_175 <= empty_fu_125_p1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_blk_n = ColorMode_empty_n;
    end else begin
        ColorMode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_read = 1'b1;
    end else begin
        ColorMode_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_c18_blk_n = Height_c18_full_n;
    end else begin
        Height_c18_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_c18_write = 1'b1;
    end else begin
        Height_c18_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthOut_blk_n = WidthOut_empty_n;
    end else begin
        WidthOut_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthOut_c22_blk_n = WidthOut_c22_full_n;
    end else begin
        WidthOut_c22_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthOut_c22_write = 1'b1;
    end else begin
        WidthOut_c22_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthOut_read = 1'b1;
    end else begin
        WidthOut_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2033_fu_147_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2033_fu_147_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_scaled_csc_write = grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_csc_write;
    end else begin
        stream_scaled_csc_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_scaled_read = grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_read;
    end else begin
        stream_scaled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2033_fu_147_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Height_c18_din = Height_dout;

assign WidthOut_c22_din = WidthOut_dout;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == WidthOut_c22_full_n) | (1'b0 == Height_c18_full_n) | (1'b0 == ColorMode_empty_n) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1));
end

assign cmp73_fu_133_p2 = ((ColorMode_dout != 8'd0) ? 1'b1 : 1'b0);

assign empty_76_fu_129_p1 = Height_dout[10:0];

assign empty_fu_125_p1 = WidthOut_dout[10:0];

assign grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start = grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_ap_start_reg;

assign icmp_ln2033_fu_147_p2 = ((y_fu_70 == empty_76_reg_180) ? 1'b1 : 1'b0);

assign stream_scaled_csc_din = grp_v_csc_core_Pipeline_VITIS_LOOP_2035_2_fu_114_stream_scaled_csc_din;

assign y_7_fu_152_p2 = (y_fu_70 + 11'd1);

endmodule //bd_eab1_hsc_0_v_csc_core
