// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_eab1_vsc_0_v_vcresampler_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        SrcYUV_dout,
        SrcYUV_num_data_valid,
        SrcYUV_fifo_cap,
        SrcYUV_empty_n,
        SrcYUV_read,
        height_dout,
        height_num_data_valid,
        height_fifo_cap,
        height_empty_n,
        height_read,
        width_dout,
        width_num_data_valid,
        width_fifo_cap,
        width_empty_n,
        width_read,
        inColorMode_dout,
        inColorMode_num_data_valid,
        inColorMode_fifo_cap,
        inColorMode_empty_n,
        inColorMode_read,
        outColorMode_dout,
        outColorMode_num_data_valid,
        outColorMode_fifo_cap,
        outColorMode_empty_n,
        outColorMode_read,
        SrcYUV422_din,
        SrcYUV422_num_data_valid,
        SrcYUV422_fifo_cap,
        SrcYUV422_full_n,
        SrcYUV422_write,
        HwReg_HeightIn_c_din,
        HwReg_HeightIn_c_num_data_valid,
        HwReg_HeightIn_c_fifo_cap,
        HwReg_HeightIn_c_full_n,
        HwReg_HeightIn_c_write,
        HwReg_Width_c16_din,
        HwReg_Width_c16_num_data_valid,
        HwReg_Width_c16_fifo_cap,
        HwReg_Width_c16_full_n,
        HwReg_Width_c16_write,
        ColorMode_vcr_c_din,
        ColorMode_vcr_c_num_data_valid,
        ColorMode_vcr_c_fifo_cap,
        ColorMode_vcr_c_full_n,
        ColorMode_vcr_c_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] SrcYUV_dout;
input  [4:0] SrcYUV_num_data_valid;
input  [4:0] SrcYUV_fifo_cap;
input   SrcYUV_empty_n;
output   SrcYUV_read;
input  [10:0] height_dout;
input  [1:0] height_num_data_valid;
input  [1:0] height_fifo_cap;
input   height_empty_n;
output   height_read;
input  [10:0] width_dout;
input  [1:0] width_num_data_valid;
input  [1:0] width_fifo_cap;
input   width_empty_n;
output   width_read;
input  [7:0] inColorMode_dout;
input  [1:0] inColorMode_num_data_valid;
input  [1:0] inColorMode_fifo_cap;
input   inColorMode_empty_n;
output   inColorMode_read;
input  [7:0] outColorMode_dout;
input  [1:0] outColorMode_num_data_valid;
input  [1:0] outColorMode_fifo_cap;
input   outColorMode_empty_n;
output   outColorMode_read;
output  [23:0] SrcYUV422_din;
input  [4:0] SrcYUV422_num_data_valid;
input  [4:0] SrcYUV422_fifo_cap;
input   SrcYUV422_full_n;
output   SrcYUV422_write;
output  [10:0] HwReg_HeightIn_c_din;
input  [1:0] HwReg_HeightIn_c_num_data_valid;
input  [1:0] HwReg_HeightIn_c_fifo_cap;
input   HwReg_HeightIn_c_full_n;
output   HwReg_HeightIn_c_write;
output  [10:0] HwReg_Width_c16_din;
input  [1:0] HwReg_Width_c16_num_data_valid;
input  [1:0] HwReg_Width_c16_fifo_cap;
input   HwReg_Width_c16_full_n;
output   HwReg_Width_c16_write;
output  [7:0] ColorMode_vcr_c_din;
input  [2:0] ColorMode_vcr_c_num_data_valid;
input  [2:0] ColorMode_vcr_c_fifo_cap;
input   ColorMode_vcr_c_full_n;
output   ColorMode_vcr_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg SrcYUV_read;
reg height_read;
reg width_read;
reg inColorMode_read;
reg outColorMode_read;
reg SrcYUV422_write;
reg HwReg_HeightIn_c_write;
reg HwReg_Width_c16_write;
reg ColorMode_vcr_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    height_blk_n;
reg    width_blk_n;
reg    inColorMode_blk_n;
reg    outColorMode_blk_n;
reg    HwReg_HeightIn_c_blk_n;
reg    HwReg_Width_c16_blk_n;
reg    ColorMode_vcr_c_blk_n;
reg   [10:0] loopWidth_reg_394;
reg   [10:0] height_read_reg_399;
wire   [0:0] icmp_ln995_fu_204_p2;
reg   [0:0] icmp_ln995_reg_404;
wire   [0:0] icmp_ln999_fu_210_p2;
reg   [0:0] icmp_ln999_reg_411;
wire   [0:0] cmp287_fu_216_p2;
reg   [0:0] cmp287_reg_417;
wire   [12:0] zext_ln971_fu_246_p1;
reg   [12:0] zext_ln971_reg_425;
wire    ap_CS_fsm_state2;
wire   [11:0] zext_ln1008_fu_250_p1;
reg   [11:0] zext_ln1008_reg_430;
wire   [11:0] add_ln1010_1_fu_257_p2;
reg   [11:0] add_ln1010_1_reg_435;
wire   [0:0] sel_tmp_fu_263_p2;
reg   [0:0] sel_tmp_reg_440;
wire   [0:0] cmp36_fu_299_p2;
reg   [0:0] cmp36_reg_448;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln1010_fu_271_p2;
wire   [0:0] cmp104_fu_305_p2;
reg   [0:0] cmp104_reg_453;
wire   [0:0] rev_fu_320_p2;
reg   [0:0] rev_reg_458;
wire   [0:0] spec_select_fu_327_p2;
reg   [0:0] spec_select_reg_463;
wire   [0:0] sel_tmp1_fu_333_p2;
reg   [0:0] sel_tmp1_reg_468;
wire   [0:0] sel_tmp4_fu_345_p2;
reg   [0:0] sel_tmp4_reg_473;
wire   [0:0] sel_tmp6_fu_351_p2;
reg   [0:0] sel_tmp6_reg_478;
wire   [7:0] linebuf_y_val_V_q1;
wire   [7:0] linebuf_y_val_V_1_q0;
wire   [7:0] linebuf_c_val_V_q1;
wire   [7:0] linebuf_c_val_V_1_q1;
wire   [7:0] linebuf_c_val_V_2_q0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_done;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_idle;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_ready;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV_read;
wire   [23:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV422_din;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV422_write;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_d0;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_address1;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_ce1;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_d0;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_d0;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_address1;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_ce1;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_d0;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_address1;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_ce1;
wire   [10:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_2_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_2_ce0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0878_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0878_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423876_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423876_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_2_0_0_0874_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_2_0_0_0874_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0872_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0872_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423870_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423870_out_o_ap_vld;
reg    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [7:0] p_0_1_0_0_0879_lcssa911_fu_100;
reg   [7:0] p_0_0_0_0_0423877_lcssa908_fu_96;
reg   [7:0] p_0_2_0_0_0875_lcssa905_fu_92;
reg   [7:0] p_0_1_0_0_0873_lcssa902_fu_88;
reg   [7:0] p_0_0_0_0_0423871_lcssa899_fu_84;
reg   [11:0] y_fu_104;
wire   [11:0] add_ln1010_fu_276_p2;
reg    ap_block_state1;
wire   [0:0] or_ln995_fu_234_p2;
wire   [1:0] select_ln995_fu_227_p3;
wire   [1:0] yOffset_fu_238_p3;
wire   [11:0] yOffset_cast_fu_253_p1;
wire   [12:0] y_cast12_fu_282_p1;
wire   [12:0] out_y_fu_290_p2;
wire   [0:0] tmp_fu_312_p3;
wire   [0:0] empty_fu_286_p1;
wire   [0:0] empty_67_fu_295_p1;
wire   [0:0] sel_tmp3_fu_339_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start_reg = 1'b0;
end

bd_eab1_vsc_0_v_vcresampler_core_linebuf_y_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_y_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_d0),
    .address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_address1),
    .ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_ce1),
    .q1(linebuf_y_val_V_q1)
);

bd_eab1_vsc_0_v_vcresampler_core_linebuf_y_val_V_1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_y_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_d0),
    .q0(linebuf_y_val_V_1_q0)
);

bd_eab1_vsc_0_v_vcresampler_core_linebuf_y_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_c_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_d0),
    .address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_address1),
    .ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_ce1),
    .q1(linebuf_c_val_V_q1)
);

bd_eab1_vsc_0_v_vcresampler_core_linebuf_y_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_c_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_d0),
    .address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_address1),
    .ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_ce1),
    .q1(linebuf_c_val_V_1_q1)
);

bd_eab1_vsc_0_v_vcresampler_core_linebuf_c_val_V_2_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_c_val_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_2_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_2_ce0),
    .q0(linebuf_c_val_V_2_q0)
);

bd_eab1_vsc_0_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2 grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start),
    .ap_done(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_done),
    .ap_idle(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_idle),
    .ap_ready(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_ready),
    .SrcYUV_dout(SrcYUV_dout),
    .SrcYUV_num_data_valid(5'd0),
    .SrcYUV_fifo_cap(5'd0),
    .SrcYUV_empty_n(SrcYUV_empty_n),
    .SrcYUV_read(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV_read),
    .SrcYUV422_din(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV422_din),
    .SrcYUV422_num_data_valid(5'd0),
    .SrcYUV422_fifo_cap(5'd0),
    .SrcYUV422_full_n(SrcYUV422_full_n),
    .SrcYUV422_write(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV422_write),
    .loopWidth(loopWidth_reg_394),
    .sel_tmp1(sel_tmp1_reg_468),
    .sel_tmp4(sel_tmp4_reg_473),
    .sel_tmp6(sel_tmp6_reg_478),
    .cmp287(cmp287_reg_417),
    .cmp391(rev_reg_458),
    .cmp104(cmp104_reg_453),
    .cmp36(cmp36_reg_448),
    .linebuf_y_val_V_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_address0),
    .linebuf_y_val_V_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_ce0),
    .linebuf_y_val_V_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_we0),
    .linebuf_y_val_V_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_d0),
    .linebuf_y_val_V_address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_address1),
    .linebuf_y_val_V_ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_ce1),
    .linebuf_y_val_V_q1(linebuf_y_val_V_q1),
    .linebuf_y_val_V_1_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_address0),
    .linebuf_y_val_V_1_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_ce0),
    .linebuf_y_val_V_1_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_we0),
    .linebuf_y_val_V_1_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_y_val_V_1_d0),
    .linebuf_y_val_V_1_q0(linebuf_y_val_V_1_q0),
    .linebuf_c_val_V_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_address0),
    .linebuf_c_val_V_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_ce0),
    .linebuf_c_val_V_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_we0),
    .linebuf_c_val_V_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_d0),
    .linebuf_c_val_V_address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_address1),
    .linebuf_c_val_V_ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_ce1),
    .linebuf_c_val_V_q1(linebuf_c_val_V_q1),
    .linebuf_c_val_V_1_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_address0),
    .linebuf_c_val_V_1_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_ce0),
    .linebuf_c_val_V_1_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_we0),
    .linebuf_c_val_V_1_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_d0),
    .linebuf_c_val_V_1_address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_address1),
    .linebuf_c_val_V_1_ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_1_ce1),
    .linebuf_c_val_V_1_q1(linebuf_c_val_V_1_q1),
    .spec_select(spec_select_reg_463),
    .linebuf_c_val_V_2_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_2_address0),
    .linebuf_c_val_V_2_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_linebuf_c_val_V_2_ce0),
    .linebuf_c_val_V_2_q0(linebuf_c_val_V_2_q0),
    .icmp_ln995(icmp_ln995_reg_404),
    .p_0_1_0_0_0878_out_i(p_0_1_0_0_0879_lcssa911_fu_100),
    .p_0_1_0_0_0878_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0878_out_o),
    .p_0_1_0_0_0878_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0878_out_o_ap_vld),
    .p_0_0_0_0_0423876_out_i(p_0_0_0_0_0423877_lcssa908_fu_96),
    .p_0_0_0_0_0423876_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423876_out_o),
    .p_0_0_0_0_0423876_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423876_out_o_ap_vld),
    .p_0_2_0_0_0874_out_i(p_0_2_0_0_0875_lcssa905_fu_92),
    .p_0_2_0_0_0874_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_2_0_0_0874_out_o),
    .p_0_2_0_0_0874_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_2_0_0_0874_out_o_ap_vld),
    .p_0_1_0_0_0872_out_i(p_0_1_0_0_0873_lcssa902_fu_88),
    .p_0_1_0_0_0872_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0872_out_o),
    .p_0_1_0_0_0872_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0872_out_o_ap_vld),
    .p_0_0_0_0_0423870_out_i(p_0_0_0_0_0423871_lcssa899_fu_84),
    .p_0_0_0_0_0423870_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423870_out_o),
    .p_0_0_0_0_0423870_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423870_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd0))) begin
            grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_ready == 1'b1)) begin
            grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_104 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd0))) begin
        y_fu_104 <= add_ln1010_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln1010_1_reg_435 <= add_ln1010_1_fu_257_p2;
        sel_tmp_reg_440 <= sel_tmp_fu_263_p2;
        zext_ln1008_reg_430[10 : 0] <= zext_ln1008_fu_250_p1[10 : 0];
        zext_ln971_reg_425[1 : 0] <= zext_ln971_fu_246_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd0))) begin
        cmp104_reg_453 <= cmp104_fu_305_p2;
        cmp36_reg_448 <= cmp36_fu_299_p2;
        rev_reg_458 <= rev_fu_320_p2;
        sel_tmp1_reg_468 <= sel_tmp1_fu_333_p2;
        sel_tmp4_reg_473 <= sel_tmp4_fu_345_p2;
        sel_tmp6_reg_478 <= sel_tmp6_fu_351_p2;
        spec_select_reg_463 <= spec_select_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp287_reg_417 <= cmp287_fu_216_p2;
        height_read_reg_399 <= height_dout;
        icmp_ln995_reg_404 <= icmp_ln995_fu_204_p2;
        icmp_ln999_reg_411 <= icmp_ln999_fu_210_p2;
        loopWidth_reg_394 <= width_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423870_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0423871_lcssa899_fu_84 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423870_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423876_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0423877_lcssa908_fu_96 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_0_0_0_0423876_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0872_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0873_lcssa902_fu_88 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0872_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0878_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0879_lcssa911_fu_100 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_1_0_0_0878_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_2_0_0_0874_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_0875_lcssa905_fu_92 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_p_0_2_0_0_0874_out_o;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_vcr_c_blk_n = ColorMode_vcr_c_full_n;
    end else begin
        ColorMode_vcr_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_vcr_c_write = 1'b1;
    end else begin
        ColorMode_vcr_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_HeightIn_c_blk_n = HwReg_HeightIn_c_full_n;
    end else begin
        HwReg_HeightIn_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_HeightIn_c_write = 1'b1;
    end else begin
        HwReg_HeightIn_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Width_c16_blk_n = HwReg_Width_c16_full_n;
    end else begin
        HwReg_Width_c16_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Width_c16_write = 1'b1;
    end else begin
        HwReg_Width_c16_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SrcYUV422_write = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV422_write;
    end else begin
        SrcYUV422_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SrcYUV_read = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV_read;
    end else begin
        SrcYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_blk_n = height_empty_n;
    end else begin
        height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_read = 1'b1;
    end else begin
        height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inColorMode_blk_n = inColorMode_empty_n;
    end else begin
        inColorMode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inColorMode_read = 1'b1;
    end else begin
        inColorMode_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        outColorMode_blk_n = outColorMode_empty_n;
    end else begin
        outColorMode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        outColorMode_read = 1'b1;
    end else begin
        outColorMode_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_blk_n = width_empty_n;
    end else begin
        width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_read = 1'b1;
    end else begin
        width_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1010_fu_271_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ColorMode_vcr_c_din = outColorMode_dout;

assign HwReg_HeightIn_c_din = height_dout;

assign HwReg_Width_c16_din = width_dout;

assign SrcYUV422_din = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_SrcYUV422_din;

assign add_ln1010_1_fu_257_p2 = (zext_ln1008_fu_250_p1 + yOffset_cast_fu_253_p1);

assign add_ln1010_fu_276_p2 = (y_fu_104 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (outColorMode_empty_n == 1'b0) | (inColorMode_empty_n == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == ColorMode_vcr_c_full_n) | (1'b0 == HwReg_Width_c16_full_n) | (1'b0 == HwReg_HeightIn_c_full_n) | (ap_done_reg == 1'b1));
end

assign cmp104_fu_305_p2 = ((y_fu_104 != 12'd0) ? 1'b1 : 1'b0);

assign cmp287_fu_216_p2 = ((inColorMode_dout == 8'd2) ? 1'b1 : 1'b0);

assign cmp36_fu_299_p2 = ((y_fu_104 < zext_ln1008_reg_430) ? 1'b1 : 1'b0);

assign empty_67_fu_295_p1 = out_y_fu_290_p2[0:0];

assign empty_fu_286_p1 = y_fu_104[0:0];

assign grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_1012_2_fu_176_ap_start_reg;

assign icmp_ln1010_fu_271_p2 = ((y_fu_104 == add_ln1010_1_reg_435) ? 1'b1 : 1'b0);

assign icmp_ln995_fu_204_p2 = ((inColorMode_dout == outColorMode_dout) ? 1'b1 : 1'b0);

assign icmp_ln999_fu_210_p2 = ((inColorMode_dout == 8'd3) ? 1'b1 : 1'b0);

assign or_ln995_fu_234_p2 = (icmp_ln999_reg_411 | icmp_ln995_reg_404);

assign out_y_fu_290_p2 = (y_cast12_fu_282_p1 - zext_ln971_reg_425);

assign rev_fu_320_p2 = (tmp_fu_312_p3 ^ 1'd1);

assign sel_tmp1_fu_333_p2 = (sel_tmp_reg_440 & empty_67_fu_295_p1);

assign sel_tmp3_fu_339_p2 = (empty_67_fu_295_p1 ^ 1'd1);

assign sel_tmp4_fu_345_p2 = (sel_tmp3_fu_339_p2 & cmp287_reg_417);

assign sel_tmp6_fu_351_p2 = (empty_67_fu_295_p1 & cmp287_reg_417);

assign sel_tmp_fu_263_p2 = (cmp287_reg_417 ^ 1'd1);

assign select_ln995_fu_227_p3 = ((icmp_ln995_reg_404[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign spec_select_fu_327_p2 = (icmp_ln999_reg_411 & empty_fu_286_p1);

assign tmp_fu_312_p3 = out_y_fu_290_p2[32'd12];

assign yOffset_cast_fu_253_p1 = yOffset_fu_238_p3;

assign yOffset_fu_238_p3 = ((or_ln995_fu_234_p2[0:0] == 1'b1) ? select_ln995_fu_227_p3 : 2'd1);

assign y_cast12_fu_282_p1 = y_fu_104;

assign zext_ln1008_fu_250_p1 = height_read_reg_399;

assign zext_ln971_fu_246_p1 = yOffset_fu_238_p3;

always @ (posedge ap_clk) begin
    zext_ln971_reg_425[12:2] <= 11'b00000000000;
    zext_ln1008_reg_430[11] <= 1'b0;
end

endmodule //bd_eab1_vsc_0_v_vcresampler_core
