set SynModuleInfo {
  {SRCNAME entry_proc MODELNAME entry_proc RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_entry_proc}
  {SRCNAME {reg<unsigned short>} MODELNAME reg_unsigned_short_s RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_reg_unsigned_short_s}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start
    SUBMODULES {
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_flow_control_loop_pipe_sequential_init RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_width MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_width RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_AXIvideo2MultiPixStream_Pipeline_loop_width}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol}
  {SRCNAME AXIvideo2MultiPixStream MODELNAME AXIvideo2MultiPixStream RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_AXIvideo2MultiPixStream}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_9 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_9 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_9}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_4 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_4 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_4}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1}
  {SRCNAME MultiPixStream2Bytes MODELNAME MultiPixStream2Bytes RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MultiPixStream2Bytes
    SUBMODULES {
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_mul_mul_12ns_13ns_25_4_1 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_mul_mul_12ns_13ns_25_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1117_1 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1117_1 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1117_1}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1127_2 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1127_2 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1127_2}
  {SRCNAME Bytes2AXIMMvideo MODELNAME Bytes2AXIMMvideo RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_Bytes2AXIMMvideo}
  {SRCNAME FrmbufWrHlsDataFlow MODELNAME FrmbufWrHlsDataFlow RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_FrmbufWrHlsDataFlow
    SUBMODULES {
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w32_d4_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME HwReg_frm_buffer_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w32_d4_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME HwReg_frm_buffer2_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w14_d3_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w14_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME WidthInBytes_c9_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w16_d4_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w16_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME stride_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w6_d3_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w6_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME video_format_c11_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w24_d2_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME img_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w3_d2_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w3_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME width_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w11_d2_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w11_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME height_c10_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w64_d480_B RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w64_d480_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME bytePlanes_plane0_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w64_d480_B RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w64_d480_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME bytePlanes_plane1_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w14_d2_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w14_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME WidthInBytes_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w11_d2_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w11_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME height_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w6_d2_S RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME video_format_c_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_start_for_MultiPixStream2Bytes_U0 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_start_for_MultiPixStream2Bytes_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_MultiPixStream2Bytes_U0_U}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_start_for_Bytes2AXIMMvideo_U0 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_start_for_Bytes2AXIMMvideo_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_Bytes2AXIMMvideo_U0_U}
    }
  }
  {SRCNAME v_frmbuf_wr MODELNAME v_frmbuf_wr RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_v_frmbuf_wr IS_TOP 1
    SUBMODULES {
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_mul_11ns_3ns_14_1_1 RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_mul_11ns_3ns_14_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_BYTES_PER_PIXEL_ROM_AUTO_1R RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_BYTES_PER_PIXEL_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MEMORY2LIVE_ROM_AUTO_1R RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_MEMORY2LIVE_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_mm_video_m_axi RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_mm_video_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_CTRL_s_axi RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_CTRL_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_regslice_both RTLNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_1_regslice_both_U}
    }
  }
}
