-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_eab1_hsc_0_Block_entry1_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    ColorMode : IN STD_LOGIC_VECTOR (7 downto 0);
    ColorModeOut : IN STD_LOGIC_VECTOR (7 downto 0);
    ColorMode_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    ColorMode_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ColorMode_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ColorMode_c_full_n : IN STD_LOGIC;
    ColorMode_c_write : OUT STD_LOGIC;
    ColorModeOut_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    ColorModeOut_c_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    ColorModeOut_c_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    ColorModeOut_c_full_n : IN STD_LOGIC;
    ColorModeOut_c_write : OUT STD_LOGIC;
    ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bd_eab1_hsc_0_Block_entry1_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ColorMode_c_blk_n : STD_LOGIC;
    signal ColorModeOut_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln110_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_1_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_3_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_1_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_1_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bPassThruHcr1_fu_74_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bPassThruCsc_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bPassThruHcr2_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bPassThruVcr_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv1_0;
            else
                if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_0_preg <= bPassThruHcr1_fu_74_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv1_0;
            else
                if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_1_preg <= bPassThruCsc_fu_122_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv1_0;
            else
                if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_2_preg <= bPassThruHcr2_fu_146_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv1_0;
            else
                if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_3_preg <= bPassThruVcr_fu_152_p2;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    ColorModeOut_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorModeOut_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ColorModeOut_c_blk_n <= ColorModeOut_c_full_n;
        else 
            ColorModeOut_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ColorModeOut_c_din <= ColorModeOut;

    ColorModeOut_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ColorModeOut_c_write <= ap_const_logic_1;
        else 
            ColorModeOut_c_write <= ap_const_logic_0;
        end if; 
    end process;


    ColorMode_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ColorMode_c_blk_n <= ColorMode_c_full_n;
        else 
            ColorMode_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ColorMode_c_din <= ColorMode;

    ColorMode_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ColorMode_c_write <= ap_const_logic_1;
        else 
            ColorMode_c_write <= ap_const_logic_0;
        end if; 
    end process;

    and_ln110_1_fu_110_p2 <= (icmp_ln110_3_fu_104_p2 and icmp_ln110_2_fu_98_p2);
    and_ln110_fu_92_p2 <= (icmp_ln110_fu_80_p2 and icmp_ln110_1_fu_86_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
        if (((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    ap_return_0_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n, bPassThruHcr1_fu_74_p2, ap_return_0_preg)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_0 <= bPassThruHcr1_fu_74_p2;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n, bPassThruCsc_fu_122_p2, ap_return_1_preg)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_1 <= bPassThruCsc_fu_122_p2;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n, bPassThruHcr2_fu_146_p2, ap_return_2_preg)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_2 <= bPassThruHcr2_fu_146_p2;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n, bPassThruVcr_fu_152_p2, ap_return_3_preg)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_3 <= bPassThruVcr_fu_152_p2;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;

    bPassThruCsc_fu_122_p2 <= (or_ln110_fu_116_p2 xor ap_const_lv1_1);
    bPassThruHcr1_fu_74_p2 <= "0" when (ColorMode = ap_const_lv8_2) else "1";
    bPassThruHcr2_fu_146_p2 <= (or_ln115_fu_140_p2 xor ap_const_lv1_1);
    bPassThruVcr_fu_152_p2 <= (icmp_ln115_1_fu_134_p2 xor ap_const_lv1_1);
    icmp_ln110_1_fu_86_p2 <= "0" when (ColorModeOut = ap_const_lv8_0) else "1";
    icmp_ln110_2_fu_98_p2 <= "0" when (ColorMode = ap_const_lv8_0) else "1";
    icmp_ln110_3_fu_104_p2 <= "1" when (ColorModeOut = ap_const_lv8_0) else "0";
    icmp_ln110_fu_80_p2 <= "1" when (ColorMode = ap_const_lv8_0) else "0";
    icmp_ln115_1_fu_134_p2 <= "1" when (ColorModeOut = ap_const_lv8_3) else "0";
    icmp_ln115_fu_128_p2 <= "1" when (ColorModeOut = ap_const_lv8_2) else "0";

    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ColorMode_c_full_n, ColorModeOut_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_const_logic_0 = ColorModeOut_c_full_n) or (ap_const_logic_0 = ColorMode_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    or_ln110_fu_116_p2 <= (and_ln110_fu_92_p2 or and_ln110_1_fu_110_p2);
    or_ln115_fu_140_p2 <= (icmp_ln115_fu_128_p2 or icmp_ln115_1_fu_134_p2);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
