-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_eab1_hsc_0_v_csc_core_Pipeline_VITIS_LOOP_2035_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_scaled_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_scaled_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_empty_n : IN STD_LOGIC;
    stream_scaled_read : OUT STD_LOGIC;
    stream_scaled_csc_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_scaled_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_csc_full_n : IN STD_LOGIC;
    stream_scaled_csc_write : OUT STD_LOGIC;
    WidthOut_load_cast : IN STD_LOGIC_VECTOR (10 downto 0);
    cmp73 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bd_eab1_hsc_0_v_csc_core_Pipeline_VITIS_LOOP_2035_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv17_132 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100110010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv11_FF : STD_LOGIC_VECTOR (10 downto 0) := "00011111111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv10_80 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_const_lv10_FF : STD_LOGIC_VECTOR (9 downto 0) := "0011111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv11_80 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_const_lv12_FF : STD_LOGIC_VECTOR (11 downto 0) := "000011111111";
    constant ap_const_lv15_75 : STD_LOGIC_VECTOR (14 downto 0) := "000000001110101";
    constant ap_const_lv20_6C5 : STD_LOGIC_VECTOR (19 downto 0) := "00000000011011000101";
    constant ap_const_lv18_253 : STD_LOGIC_VECTOR (17 downto 0) := "000000001001010011";
    constant ap_const_lv18_259 : STD_LOGIC_VECTOR (17 downto 0) := "000000001001011001";
    constant ap_const_lv18_194 : STD_LOGIC_VECTOR (17 downto 0) := "000000000110010100";
    constant ap_const_lv21_821 : STD_LOGIC_VECTOR (20 downto 0) := "000000000100000100001";
    constant ap_const_lv20_382 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001110000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln2035_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_scaled_csc_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_scaled_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal cmp73_read_reg_621 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_y_V_fu_179_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_V_reg_632 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_V_reg_632_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_V_reg_632_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_V_reg_632_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_V_reg_632_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal g_u_V_reg_641 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_u_V_reg_641_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_v_V_fu_193_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_v_V_reg_647 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_v_V_reg_647_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_v_V_reg_647_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_v_V_reg_647_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln2056_fu_239_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_572_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln8_reg_698 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln2060_fu_356_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln2060_reg_708 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln2060_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2060_reg_713 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_fu_404_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal b_reg_718 : STD_LOGIC_VECTOR (11 downto 0);
    signal b_reg_718_pp0_iter7_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln214_fu_435_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_reg_723 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_reg_723_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_reg_723_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln2062_fu_450_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln2062_reg_728 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln2062_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2062_reg_733 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln214_1_fu_476_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_1_reg_738 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_1_reg_738_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln2064_fu_513_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln2064_reg_743 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln2064_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2064_reg_748 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_118 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_4_fu_168_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_s_fu_547_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal Cr_fu_207_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Cb_fu_223_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln2056_fu_239_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln2056_fu_239_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_556_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_565_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln_fu_257_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln2051_fu_266_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln2051_4_fu_254_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_578_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln7_fu_276_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln2049_fu_248_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln2056_3_fu_289_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln2057_fu_293_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_fu_299_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln2057_1_fu_311_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln2057_fu_307_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln2057_1_fu_319_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln2057_1_fu_323_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln2051_fu_251_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln2058_fu_339_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_fu_270_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln2056_2_fu_285_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln2060_fu_349_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_587_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln5_fu_372_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln2051_3_fu_369_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln2052_1_fu_381_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_596_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln6_fu_391_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln2053_fu_400_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln2051_2_fu_366_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln2057_2_fu_410_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln2060_1_fu_419_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln2060_1_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln214_fu_431_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_fu_385_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal u_fu_413_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln2062_fu_443_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln2062_1_fu_460_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln2062_1_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln214_1_fu_472_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_603_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln9_fu_484_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln2058_1_fu_493_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal v_fu_497_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln2058_2_fu_503_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln2064_fu_507_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln2064_1_fu_523_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln2064_1_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln214_2_fu_535_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_2_fu_539_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_556_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_556_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_565_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_572_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_578_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_578_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_578_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_587_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_596_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_603_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_556_ce : STD_LOGIC;
    signal grp_fu_565_ce : STD_LOGIC;
    signal grp_fu_572_ce : STD_LOGIC;
    signal grp_fu_578_ce : STD_LOGIC;
    signal grp_fu_587_ce : STD_LOGIC;
    signal grp_fu_596_ce : STD_LOGIC;
    signal grp_fu_603_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_556_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_578_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_578_p20 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln2056_fu_239_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_condition_640 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component bd_eab1_hsc_0_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component bd_eab1_hsc_0_mac_muladd_8ns_7ns_17ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component bd_eab1_hsc_0_mul_mul_8s_11ns_20_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component bd_eab1_hsc_0_mul_mul_8s_10ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component bd_eab1_hsc_0_mac_muladd_8ns_10ns_17ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component bd_eab1_hsc_0_mac_muladd_8s_9ns_18s_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component bd_eab1_hsc_0_mul_mul_8s_12ns_21_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component bd_eab1_hsc_0_mul_mul_9s_10ns_20_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component bd_eab1_hsc_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_10ns_17_1_1_U221 : component bd_eab1_hsc_0_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln2056_fu_239_p0,
        din1 => mul_ln2056_fu_239_p1,
        dout => mul_ln2056_fu_239_p2);

    mac_muladd_8ns_7ns_17ns_17_4_1_U222 : component bd_eab1_hsc_0_mac_muladd_8ns_7ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_556_p0,
        din1 => grp_fu_556_p1,
        din2 => mul_ln2056_fu_239_p2,
        ce => grp_fu_556_ce,
        dout => grp_fu_556_p3);

    mul_mul_8s_11ns_20_4_1_U223 : component bd_eab1_hsc_0_mul_mul_8s_11ns_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cr_fu_207_p2,
        din1 => grp_fu_565_p1,
        ce => grp_fu_565_ce,
        dout => grp_fu_565_p2);

    mul_mul_8s_10ns_18_4_1_U224 : component bd_eab1_hsc_0_mul_mul_8s_10ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cr_fu_207_p2,
        din1 => grp_fu_572_p1,
        ce => grp_fu_572_ce,
        dout => grp_fu_572_p2);

    mac_muladd_8ns_10ns_17ns_18_4_1_U225 : component bd_eab1_hsc_0_mac_muladd_8ns_10ns_17ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        din2_WIDTH => 17,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_578_p0,
        din1 => grp_fu_578_p1,
        din2 => grp_fu_578_p2,
        ce => grp_fu_578_ce,
        dout => grp_fu_578_p3);

    mac_muladd_8s_9ns_18s_18_4_1_U226 : component bd_eab1_hsc_0_mac_muladd_8s_9ns_18s_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        din2_WIDTH => 18,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cb_fu_223_p2,
        din1 => grp_fu_587_p1,
        din2 => grp_fu_572_p2,
        ce => grp_fu_587_ce,
        dout => grp_fu_587_p3);

    mul_mul_8s_12ns_21_4_1_U227 : component bd_eab1_hsc_0_mul_mul_8s_12ns_21_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 12,
        dout_WIDTH => 21)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cb_fu_223_p2,
        din1 => grp_fu_596_p1,
        ce => grp_fu_596_ce,
        dout => grp_fu_596_p2);

    mul_mul_9s_10ns_20_4_1_U228 : component bd_eab1_hsc_0_mul_mul_9s_10ns_20_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 9,
        din1_WIDTH => 10,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_ln2058_fu_339_p2,
        din1 => grp_fu_603_p1,
        ce => grp_fu_603_ce,
        dout => grp_fu_603_p2);

    flow_control_loop_pipe_sequential_init_U : component bd_eab1_hsc_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    x_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln2035_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_118 <= x_4_fu_168_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_118 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                b_v_V_reg_647 <= stream_scaled_dout(23 downto 16);
                g_u_V_reg_641 <= stream_scaled_dout(15 downto 8);
                r_y_V_reg_632 <= r_y_V_fu_179_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                b_reg_718_pp0_iter7_reg <= b_reg_718;
                b_v_V_reg_647_pp0_iter2_reg <= b_v_V_reg_647;
                b_v_V_reg_647_pp0_iter3_reg <= b_v_V_reg_647_pp0_iter2_reg;
                b_v_V_reg_647_pp0_iter4_reg <= b_v_V_reg_647_pp0_iter3_reg;
                g_u_V_reg_641_pp0_iter2_reg <= g_u_V_reg_641;
                icmp_ln2060_reg_713 <= icmp_ln2060_fu_360_p2;
                icmp_ln2062_reg_733 <= icmp_ln2062_fu_454_p2;
                icmp_ln2064_reg_748 <= icmp_ln2064_fu_517_p2;
                r_y_V_reg_632_pp0_iter2_reg <= r_y_V_reg_632;
                r_y_V_reg_632_pp0_iter3_reg <= r_y_V_reg_632_pp0_iter2_reg;
                r_y_V_reg_632_pp0_iter4_reg <= r_y_V_reg_632_pp0_iter3_reg;
                r_y_V_reg_632_pp0_iter5_reg <= r_y_V_reg_632_pp0_iter4_reg;
                select_ln214_1_reg_738 <= select_ln214_1_fu_476_p3;
                select_ln214_1_reg_738_pp0_iter8_reg <= select_ln214_1_reg_738;
                select_ln214_reg_723 <= select_ln214_fu_435_p3;
                select_ln214_reg_723_pp0_iter7_reg <= select_ln214_reg_723;
                select_ln214_reg_723_pp0_iter8_reg <= select_ln214_reg_723_pp0_iter7_reg;
                trunc_ln2060_reg_708 <= trunc_ln2060_fu_356_p1;
                trunc_ln2062_reg_728 <= trunc_ln2062_fu_450_p1;
                trunc_ln2064_reg_743 <= trunc_ln2064_fu_513_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp73_read_reg_621 = ap_const_lv1_1))) then
                b_reg_718 <= b_fu_404_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (cmp73_read_reg_621 = ap_const_lv1_0))) then
                trunc_ln8_reg_698 <= sub_ln2057_1_fu_323_p2(18 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Cb_fu_223_p2 <= (g_u_V_reg_641_pp0_iter2_reg xor ap_const_lv8_80);
    Cr_fu_207_p2 <= (b_v_V_reg_647 xor ap_const_lv8_80);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, stream_scaled_empty_n, stream_scaled_csc_full_n, p_read)
    begin
                ap_block_pp0_stage0_01001 <= (((p_read = ap_const_lv1_0) and (stream_scaled_csc_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((stream_scaled_empty_n = ap_const_logic_0) or ((p_read = ap_const_lv1_1) and (stream_scaled_csc_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, stream_scaled_empty_n, stream_scaled_csc_full_n, p_read)
    begin
                ap_block_pp0_stage0_11001 <= (((p_read = ap_const_lv1_0) and (stream_scaled_csc_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((stream_scaled_empty_n = ap_const_logic_0) or ((p_read = ap_const_lv1_1) and (stream_scaled_csc_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, stream_scaled_empty_n, stream_scaled_csc_full_n, p_read)
    begin
                ap_block_pp0_stage0_subdone <= (((p_read = ap_const_lv1_0) and (stream_scaled_csc_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((stream_scaled_empty_n = ap_const_logic_0) or ((p_read = ap_const_lv1_1) and (stream_scaled_csc_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(stream_scaled_csc_full_n, p_read)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((p_read = ap_const_lv1_0) and (stream_scaled_csc_full_n = ap_const_logic_0));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(stream_scaled_empty_n, stream_scaled_csc_full_n, p_read)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((stream_scaled_empty_n = ap_const_logic_0) or ((p_read = ap_const_lv1_1) and (stream_scaled_csc_full_n = ap_const_logic_0)));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_640_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, p_read)
    begin
                ap_condition_640 <= ((p_read = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln2035_fu_162_p2)
    begin
        if (((icmp_ln2035_fu_162_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_118, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_3 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_x_3 <= x_fu_118;
        end if; 
    end process;

    b_fu_404_p2 <= std_logic_vector(signed(sext_ln2053_fu_400_p1) + signed(zext_ln2051_2_fu_366_p1));
    b_v_V_fu_193_p4 <= stream_scaled_dout(23 downto 16);
    cmp73_read_reg_621 <= cmp73;
    g_fu_385_p2 <= std_logic_vector(unsigned(zext_ln2051_3_fu_369_p1) - unsigned(sext_ln2052_1_fu_381_p1));

    grp_fu_556_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_556_ce <= ap_const_logic_1;
        else 
            grp_fu_556_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_556_p0 <= grp_fu_556_p00(8 - 1 downto 0);
    grp_fu_556_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_v_V_fu_193_p4),15));
    grp_fu_556_p1 <= ap_const_lv15_75(7 - 1 downto 0);

    grp_fu_565_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_565_ce <= ap_const_logic_1;
        else 
            grp_fu_565_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_565_p1 <= ap_const_lv20_6C5(11 - 1 downto 0);

    grp_fu_572_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_572_ce <= ap_const_logic_1;
        else 
            grp_fu_572_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_572_p1 <= ap_const_lv18_253(10 - 1 downto 0);

    grp_fu_578_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_578_ce <= ap_const_logic_1;
        else 
            grp_fu_578_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_578_p0 <= grp_fu_578_p00(8 - 1 downto 0);
    grp_fu_578_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_u_V_reg_641),18));
    grp_fu_578_p1 <= ap_const_lv18_259(10 - 1 downto 0);
    grp_fu_578_p2 <= grp_fu_578_p20(17 - 1 downto 0);
    grp_fu_578_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_556_p3),18));

    grp_fu_587_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_587_ce <= ap_const_logic_1;
        else 
            grp_fu_587_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_587_p1 <= ap_const_lv18_194(9 - 1 downto 0);

    grp_fu_596_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_596_ce <= ap_const_logic_1;
        else 
            grp_fu_596_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_596_p1 <= ap_const_lv21_821(12 - 1 downto 0);

    grp_fu_603_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_603_ce <= ap_const_logic_1;
        else 
            grp_fu_603_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_603_p1 <= ap_const_lv20_382(10 - 1 downto 0);
    icmp_ln2035_fu_162_p2 <= "1" when (ap_sig_allocacmp_x_3 = WidthOut_load_cast) else "0";
    icmp_ln2060_1_fu_425_p2 <= "1" when (signed(select_ln2060_1_fu_419_p3) > signed(ap_const_lv10_0)) else "0";
    icmp_ln2060_fu_360_p2 <= "1" when (signed(select_ln2060_fu_349_p3) < signed(ap_const_lv11_FF)) else "0";
    icmp_ln2062_1_fu_466_p2 <= "1" when (signed(select_ln2062_1_fu_460_p3) > signed(ap_const_lv9_0)) else "0";
    icmp_ln2062_fu_454_p2 <= "1" when (signed(select_ln2062_fu_443_p3) < signed(ap_const_lv10_FF)) else "0";
    icmp_ln2064_1_fu_529_p2 <= "1" when (signed(select_ln2064_1_fu_523_p3) > signed(ap_const_lv11_0)) else "0";
    icmp_ln2064_fu_517_p2 <= "1" when (signed(select_ln2064_fu_507_p3) < signed(ap_const_lv12_FF)) else "0";
    mul_ln2056_fu_239_p0 <= mul_ln2056_fu_239_p00(8 - 1 downto 0);
    mul_ln2056_fu_239_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_V_reg_632_pp0_iter2_reg),17));
    mul_ln2056_fu_239_p1 <= ap_const_lv17_132(10 - 1 downto 0);
    p_s_fu_547_p4 <= ((select_ln214_2_fu_539_p3 & select_ln214_1_reg_738_pp0_iter8_reg) & select_ln214_reg_723_pp0_iter8_reg);
    r_fu_270_p2 <= std_logic_vector(signed(sext_ln2051_fu_266_p1) + signed(zext_ln2051_4_fu_254_p1));
    r_y_V_fu_179_p1 <= stream_scaled_dout(8 - 1 downto 0);
    select_ln2060_1_fu_419_p3 <= 
        trunc_ln2060_reg_708 when (icmp_ln2060_reg_713(0) = '1') else 
        ap_const_lv10_FF;
    select_ln2060_fu_349_p3 <= 
        r_fu_270_p2 when (cmp73(0) = '1') else 
        zext_ln2056_2_fu_285_p1;
    select_ln2062_1_fu_460_p3 <= 
        trunc_ln2062_reg_728 when (icmp_ln2062_reg_733(0) = '1') else 
        ap_const_lv9_FF;
    select_ln2062_fu_443_p3 <= 
        g_fu_385_p2 when (cmp73(0) = '1') else 
        u_fu_413_p2;
    select_ln2064_1_fu_523_p3 <= 
        trunc_ln2064_reg_743 when (icmp_ln2064_reg_748(0) = '1') else 
        ap_const_lv11_FF;
    select_ln2064_fu_507_p3 <= 
        b_reg_718_pp0_iter7_reg when (cmp73(0) = '1') else 
        sext_ln2058_2_fu_503_p1;
    select_ln214_1_fu_476_p3 <= 
        trunc_ln214_1_fu_472_p1 when (icmp_ln2062_1_fu_466_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln214_2_fu_539_p3 <= 
        trunc_ln214_2_fu_535_p1 when (icmp_ln2064_1_fu_529_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln214_fu_435_p3 <= 
        trunc_ln214_fu_431_p1 when (icmp_ln2060_1_fu_425_p2(0) = '1') else 
        ap_const_lv8_0;
        sext_ln2051_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_257_p4),11));

        sext_ln2052_1_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln5_fu_372_p4),10));

        sext_ln2053_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln6_fu_391_p4),12));

        sext_ln2057_1_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln2057_1_fu_311_p3),19));

        sext_ln2057_2_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln8_reg_698),10));

        sext_ln2057_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_299_p3),19));

        sext_ln2058_1_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln9_fu_484_p4),11));

        sext_ln2058_2_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(v_fu_497_p2),12));

    shl_ln2057_1_fu_311_p3 <= (sub_ln2057_fu_293_p2 & ap_const_lv3_0);
    shl_ln_fu_299_p3 <= (sub_ln2057_fu_293_p2 & ap_const_lv9_0);

    stream_scaled_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_scaled_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_scaled_blk_n <= stream_scaled_empty_n;
        else 
            stream_scaled_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_scaled_csc_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, stream_scaled_csc_full_n, p_read, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (p_read = ap_const_lv1_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (p_read = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_scaled_csc_blk_n <= stream_scaled_csc_full_n;
        else 
            stream_scaled_csc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_scaled_csc_din_assign_proc : process(ap_enable_reg_pp0_iter9, stream_scaled_dout, p_read, ap_block_pp0_stage0_01001, p_s_fu_547_p4, ap_condition_640)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_01001)) then
            if (((p_read = ap_const_lv1_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
                stream_scaled_csc_din <= p_s_fu_547_p4;
            elsif ((ap_const_boolean_1 = ap_condition_640)) then 
                stream_scaled_csc_din <= stream_scaled_dout;
            else 
                stream_scaled_csc_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            stream_scaled_csc_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_scaled_csc_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, p_read, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_read = ap_const_lv1_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_read = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_scaled_csc_write <= ap_const_logic_1;
        else 
            stream_scaled_csc_write <= ap_const_logic_0;
        end if; 
    end process;


    stream_scaled_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_scaled_read <= ap_const_logic_1;
        else 
            stream_scaled_read <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln2057_1_fu_323_p2 <= std_logic_vector(signed(sext_ln2057_fu_307_p1) - signed(sext_ln2057_1_fu_319_p1));
    sub_ln2057_fu_293_p2 <= std_logic_vector(unsigned(zext_ln2049_fu_248_p1) - unsigned(zext_ln2056_3_fu_289_p1));
    sub_ln2058_fu_339_p2 <= std_logic_vector(unsigned(zext_ln2051_fu_251_p1) - unsigned(zext_ln2056_3_fu_289_p1));
    trunc_ln2060_fu_356_p1 <= select_ln2060_fu_349_p3(10 - 1 downto 0);
    trunc_ln2062_fu_450_p1 <= select_ln2062_fu_443_p3(9 - 1 downto 0);
    trunc_ln2064_fu_513_p1 <= select_ln2064_fu_507_p3(11 - 1 downto 0);
    trunc_ln214_1_fu_472_p1 <= select_ln2062_1_fu_460_p3(8 - 1 downto 0);
    trunc_ln214_2_fu_535_p1 <= select_ln2064_1_fu_523_p3(8 - 1 downto 0);
    trunc_ln214_fu_431_p1 <= select_ln2060_1_fu_419_p3(8 - 1 downto 0);
    trunc_ln5_fu_372_p4 <= grp_fu_587_p3(17 downto 10);
    trunc_ln6_fu_391_p4 <= grp_fu_596_p2(20 downto 10);
    trunc_ln7_fu_276_p4 <= grp_fu_578_p3(17 downto 10);
    trunc_ln9_fu_484_p4 <= grp_fu_603_p2(19 downto 10);
    trunc_ln_fu_257_p4 <= grp_fu_565_p2(19 downto 10);
    u_fu_413_p2 <= std_logic_vector(signed(sext_ln2057_2_fu_410_p1) + signed(ap_const_lv10_80));
    v_fu_497_p2 <= std_logic_vector(signed(sext_ln2058_1_fu_493_p1) + signed(ap_const_lv11_80));
    x_4_fu_168_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_3) + unsigned(ap_const_lv11_1));
    zext_ln2049_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_v_V_reg_647_pp0_iter4_reg),9));
    zext_ln2051_2_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_V_reg_632_pp0_iter5_reg),12));
    zext_ln2051_3_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_V_reg_632_pp0_iter5_reg),10));
    zext_ln2051_4_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_V_reg_632_pp0_iter4_reg),11));
    zext_ln2051_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_V_reg_632_pp0_iter4_reg),9));
    zext_ln2056_2_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln7_fu_276_p4),11));
    zext_ln2056_3_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln7_fu_276_p4),9));
end behav;
